// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package authq

import (
	"context"
)

const permissionKeys = `-- name: PermissionKeys :many
SELECT key FROM permissions ORDER BY key
`

func (q *Queries) PermissionKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
