// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package authq

import (
	"context"
	"time"
)

const invalidateResetTokens = `-- name: InvalidateResetTokens :exec
UPDATE password_reset_tokens SET used_at = now(), updated_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateResetTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, invalidateResetTokens, userID)
	return err
}

const resetActiveUserPassword = `-- name: ResetActiveUserPassword :one
UPDATE users SET password_hash = $2, sessions_valid_from = now(), updated_at = now()
WHERE id = $1 AND is_active RETURNING sessions_valid_from
`

type ResetActiveUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) ResetActiveUserPassword(ctx context.Context, arg ResetActiveUserPasswordParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, resetActiveUserPassword, arg.ID, arg.PasswordHash)
	var sessions_valid_from time.Time
	err := row.Scan(&sessions_valid_from)
	return sessions_valid_from, err
}

const verifyTokenSpent = `-- name: VerifyTokenSpent :one
SELECT (used_at IS NOT NULL)::bool AS spent FROM email_verification_tokens
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) VerifyTokenSpent(ctx context.Context, tokenHash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, verifyTokenSpent, tokenHash)
	var spent bool
	err := row.Scan(&spent)
	return spent, err
}
