// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package authq

import (
	"context"
)

const countSocialAccounts = `-- name: CountSocialAccounts :one
SELECT count(*) FROM social_accounts WHERE user_id = $1
`

func (q *Queries) CountSocialAccounts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSocialAccounts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasPassword = `-- name: HasPassword :one
SELECT password_hash <> '' AS has_password FROM users WHERE id = $1
`

func (q *Queries) HasPassword(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPassword, id)
	var has_password bool
	err := row.Scan(&has_password)
	return has_password, err
}

const linkSocial = `-- name: LinkSocial :exec
INSERT INTO social_accounts (user_id, provider, provider_uid) VALUES ($1, $2, $3)
`

type LinkSocialParams struct {
	UserID      string
	Provider    string
	ProviderUid string
}

func (q *Queries) LinkSocial(ctx context.Context, arg LinkSocialParams) error {
	_, err := q.db.Exec(ctx, linkSocial, arg.UserID, arg.Provider, arg.ProviderUid)
	return err
}

const lockUserHasPassword = `-- name: LockUserHasPassword :one
SELECT password_hash <> '' AS has_password FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserHasPassword(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, lockUserHasPassword, id)
	var has_password bool
	err := row.Scan(&has_password)
	return has_password, err
}

const socialAccounts = `-- name: SocialAccounts :many
SELECT provider, provider_uid FROM social_accounts
WHERE user_id = $1 ORDER BY provider
`

type SocialAccountsRow struct {
	Provider    string
	ProviderUid string
}

func (q *Queries) SocialAccounts(ctx context.Context, userID string) ([]SocialAccountsRow, error) {
	rows, err := q.db.Query(ctx, socialAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccountsRow{}
	for rows.Next() {
		var i SocialAccountsRow
		if err := rows.Scan(&i.Provider, &i.ProviderUid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkSocial = `-- name: UnlinkSocial :execrows
DELETE FROM social_accounts WHERE user_id = $1 AND provider = $2
`

type UnlinkSocialParams struct {
	UserID   string
	Provider string
}

func (q *Queries) UnlinkSocial(ctx context.Context, arg UnlinkSocialParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkSocial, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userIDBySocial = `-- name: UserIDBySocial :one
SELECT user_id FROM social_accounts WHERE provider = $1 AND provider_uid = $2
`

type UserIDBySocialParams struct {
	Provider    string
	ProviderUid string
}

func (q *Queries) UserIDBySocial(ctx context.Context, arg UserIDBySocialParams) (string, error) {
	row := q.db.QueryRow(ctx, userIDBySocial, arg.Provider, arg.ProviderUid)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
