// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package authq

import (
	"context"
	"time"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET is_active = true, updated_at = now() WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1::uuid, r.id FROM roles r WHERE r.key = $2 AND r.is_assignable
ON CONFLICT ON CONSTRAINT user_roles_uniq DO NOTHING
`

type AssignRoleParams struct {
	UserID  string
	RoleKey string
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleKey)
	return err
}

const boardsWithGrants = `-- name: BoardsWithGrants :many
SELECT DISTINCT board_id::text AS board_id FROM role_permissions WHERE board_id IS NOT NULL
`

func (q *Queries) BoardsWithGrants(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, boardsWithGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var board_id string
		if err := rows.Scan(&board_id); err != nil {
			return nil, err
		}
		items = append(items, board_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3) RETURNING id
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var id string
	err := row.Scan(&id)
	return id, err
}

const customFields = `-- name: CustomFields :one
SELECT custom_fields FROM users WHERE id = $1
`

func (q *Queries) CustomFields(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, customFields, id)
	var custom_fields []byte
	err := row.Scan(&custom_fields)
	return custom_fields, err
}

const dBNow = `-- name: DBNow :one
SELECT now()::timestamptz AS now
`

func (q *Queries) DBNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, dBNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id, email, display_name, is_active, sessions_valid_from,
       email_verified_at, password_hash
FROM users
WHERE email = $1 AND is_active
`

type FindActiveUserByEmailRow struct {
	ID                string
	Email             string
	DisplayName       string
	IsActive          bool
	SessionsValidFrom time.Time
	EmailVerifiedAt   *time.Time
	PasswordHash      string
}

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email string) (FindActiveUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findActiveUserByEmail, email)
	var i FindActiveUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.SessionsValidFrom,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, display_name, is_active, sessions_valid_from, email_verified_at
FROM users WHERE id = $1
`

type FindUserByIDRow struct {
	ID                string
	Email             string
	DisplayName       string
	IsActive          bool
	SessionsValidFrom time.Time
	EmailVerifiedAt   *time.Time
}

func (q *Queries) FindUserByID(ctx context.Context, id string) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.SessionsValidFrom,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const grantPermission = `-- name: GrantPermission :exec
INSERT INTO role_permissions (role_id, permission_id, board_id)
SELECT r.id, p.id, NULLIF($1::text, '')::uuid FROM roles r, permissions p
WHERE r.key = $2 AND p.key = $3
ON CONFLICT ON CONSTRAINT role_permissions_uniq DO NOTHING
`

type GrantPermissionParams struct {
	Board   string
	RoleKey string
	PermKey string
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) error {
	_, err := q.db.Exec(ctx, grantPermission, arg.Board, arg.RoleKey, arg.PermKey)
	return err
}

const holdsSuperuser = `-- name: HoldsSuperuser :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1 AND r.is_superuser
) AS holds
`

func (q *Queries) HoldsSuperuser(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, holdsSuperuser, userID)
	var holds bool
	err := row.Scan(&holds)
	return holds, err
}

const invalidateSessions = `-- name: InvalidateSessions :exec
UPDATE users SET sessions_valid_from = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) InvalidateSessions(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, invalidateSessions, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.display_name, u.is_active,
       (u.email_verified_at IS NOT NULL)::bool AS verified,
       coalesce(array_agg(r.key ORDER BY r.key) FILTER (WHERE r.key IS NOT NULL), '{}')::text[] AS roles,
       u.custom_fields
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
GROUP BY u.id
ORDER BY u.created_at DESC, u.id
LIMIT $2::int OFFSET $1::int
`

type ListUsersParams struct {
	Offset int32
	Limit  int32
}

type ListUsersRow struct {
	ID           string
	Email        string
	DisplayName  string
	IsActive     bool
	Verified     bool
	Roles        []string
	CustomFields []byte
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.Verified,
			&i.Roles,
			&i.CustomFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAnonymousPermissions = `-- name: LoadAnonymousPermissions :one
SELECT coalesce(
    array_agg(p.key || ' ' || coalesce(rp.board_id::text, ''))
        FILTER (WHERE p.key IS NOT NULL),
    '{}')::text[] AS perms
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p       ON p.id = rp.permission_id
WHERE r.key = 'anonymous'
`

func (q *Queries) LoadAnonymousPermissions(ctx context.Context) ([]string, error) {
	row := q.db.QueryRow(ctx, loadAnonymousPermissions)
	var perms []string
	err := row.Scan(&perms)
	return perms, err
}

const loadPermissions = `-- name: LoadPermissions :one
WITH effective AS (
    SELECT r.id, r.is_superuser
    FROM roles r
    WHERE r.key IN ('anonymous', 'member')
       OR r.id IN (SELECT ur.role_id FROM user_roles ur WHERE ur.user_id = $1)
)
SELECT
    coalesce(bool_or(e.is_superuser), false)::bool AS superuser,
    coalesce(
        array_agg(p.key || ' ' || coalesce(rp.board_id::text, ''))
            FILTER (WHERE p.key IS NOT NULL),
        '{}'
    )::text[] AS perms
FROM effective e
LEFT JOIN role_permissions rp ON rp.role_id = e.id
LEFT JOIN permissions p       ON p.id = rp.permission_id
`

type LoadPermissionsRow struct {
	Superuser bool
	Perms     []string
}

func (q *Queries) LoadPermissions(ctx context.Context, userID string) (LoadPermissionsRow, error) {
	row := q.db.QueryRow(ctx, loadPermissions, userID)
	var i LoadPermissionsRow
	err := row.Scan(&i.Superuser, &i.Perms)
	return i, err
}

const lockSuperuserHolders = `-- name: LockSuperuserHolders :many
SELECT u.id
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r       ON r.id = ur.role_id
WHERE r.is_superuser AND u.is_active
FOR UPDATE
`

func (q *Queries) LockSuperuserHolders(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lockSuperuserHolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permissionIsScoped = `-- name: PermissionIsScoped :one
SELECT is_scoped FROM permissions WHERE key = $1
`

func (q *Queries) PermissionIsScoped(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, permissionIsScoped, key)
	var is_scoped bool
	err := row.Scan(&is_scoped)
	return is_scoped, err
}

const roleByKey = `-- name: RoleByKey :one
SELECT r.key, r.is_superuser,
       coalesce(array_agg(p.key) FILTER (WHERE p.key IS NOT NULL), '{}')::text[] AS permissions
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p       ON p.id = rp.permission_id
WHERE r.key = $1
GROUP BY r.id, r.key, r.is_superuser
`

type RoleByKeyRow struct {
	Key         string
	IsSuperuser bool
	Permissions []string
}

func (q *Queries) RoleByKey(ctx context.Context, key string) (RoleByKeyRow, error) {
	row := q.db.QueryRow(ctx, roleByKey, key)
	var i RoleByKeyRow
	err := row.Scan(&i.Key, &i.IsSuperuser, &i.Permissions)
	return i, err
}

const roles = `-- name: Roles :many
SELECT r.key, r.name, r.is_superuser,
       coalesce(array_agg(p.key) FILTER (WHERE p.key IS NOT NULL), '{}')::text[] AS permissions
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p       ON p.id = rp.permission_id
GROUP BY r.id, r.key, r.name, r.is_superuser
ORDER BY r.key
`

type RolesRow struct {
	Key         string
	Name        string
	IsSuperuser bool
	Permissions []string
}

func (q *Queries) Roles(ctx context.Context) ([]RolesRow, error) {
	rows, err := q.db.Query(ctx, roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolesRow{}
	for rows.Next() {
		var i RolesRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.IsSuperuser,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :execrows
UPDATE users SET display_name = $2, custom_fields = $3, updated_at = now()
WHERE id = $1
`

type UpdateProfileParams struct {
	ID           string
	DisplayName  string
	CustomFields []byte
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfile, arg.ID, arg.DisplayName, arg.CustomFields)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
