// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package authq

import (
	"context"
	"time"
)

const burnUnusedResetTokens = `-- name: BurnUnusedResetTokens :exec

UPDATE password_reset_tokens SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

// 토큰 테이블은 둘(D30)이고 sqlc 질의는 테이블명을 바인딩할 수 없으므로 같은
// 문장을 테이블마다 한 벌씩 둔다. 어느 벌을 쓸지는 token.go 가 TokenKind 로 고른다.
func (q *Queries) BurnUnusedResetTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, burnUnusedResetTokens, userID)
	return err
}

const burnUnusedVerifyTokens = `-- name: BurnUnusedVerifyTokens :exec
UPDATE email_verification_tokens SET used_at = now()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) BurnUnusedVerifyTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, burnUnusedVerifyTokens, userID)
	return err
}

const consumeResetToken = `-- name: ConsumeResetToken :one
UPDATE password_reset_tokens SET used_at = now(), updated_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeResetToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeResetToken, tokenHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeVerifyToken = `-- name: ConsumeVerifyToken :one
UPDATE email_verification_tokens SET used_at = now(), updated_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeVerifyToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeVerifyToken, tokenHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const insertResetToken = `-- name: InsertResetToken :exec
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type InsertResetTokenParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertResetToken(ctx context.Context, arg InsertResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const insertVerifyToken = `-- name: InsertVerifyToken :exec
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type InsertVerifyTokenParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertVerifyToken(ctx context.Context, arg InsertVerifyTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerifyToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setPassword = `-- name: SetPassword :one
UPDATE users SET password_hash = $2, sessions_valid_from = now(), updated_at = now()
WHERE id = $1 RETURNING sessions_valid_from
`

type SetPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, setPassword, arg.ID, arg.PasswordHash)
	var sessions_valid_from time.Time
	err := row.Scan(&sessions_valid_from)
	return sessions_valid_from, err
}
