// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package commerceq

import (
	"context"
)

const cartIDForGuest = `-- name: CartIDForGuest :one
INSERT INTO carts (guest_key) VALUES ($1)
ON CONFLICT (guest_key) WHERE guest_key IS NOT NULL
DO UPDATE SET updated_at = now() RETURNING id
`

func (q *Queries) CartIDForGuest(ctx context.Context, guestKey *string) (string, error) {
	row := q.db.QueryRow(ctx, cartIDForGuest, guestKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const cartIDForUser = `-- name: CartIDForUser :one

INSERT INTO carts (user_id) VALUES ($1)
ON CONFLICT (user_id) WHERE user_id IS NOT NULL
DO UPDATE SET updated_at = now() RETURNING id
`

// 장바구니 (cart.go). 소유권 술어는 WHERE 에 있다 (SC-3) — 세 문장에 같은 조각이 그대로 적혀 있다.
func (q *Queries) CartIDForUser(ctx context.Context, userID *string) (string, error) {
	row := q.db.QueryRow(ctx, cartIDForUser, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const cartItemQuantity = `-- name: CartItemQuantity :one
SELECT quantity FROM cart_items WHERE cart_id = $1 AND variant_id = $2
`

type CartItemQuantityParams struct {
	CartID    string
	VariantID string
}

func (q *Queries) CartItemQuantity(ctx context.Context, arg CartItemQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, cartItemQuantity, arg.CartID, arg.VariantID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const cartItemVariant = `-- name: CartItemVariant :one
SELECT ci.variant_id FROM cart_items ci WHERE ci.id = $1 AND
    ci.cart_id IN (SELECT id FROM carts
                   WHERE ($2::uuid IS NOT NULL AND user_id = $2)
                      OR ($3::text IS NOT NULL AND guest_key = $3))
`

type CartItemVariantParams struct {
	ID       string
	UserID   *string
	GuestKey *string
}

func (q *Queries) CartItemVariant(ctx context.Context, arg CartItemVariantParams) (string, error) {
	row := q.db.QueryRow(ctx, cartItemVariant, arg.ID, arg.UserID, arg.GuestKey)
	var variant_id string
	err := row.Scan(&variant_id)
	return variant_id, err
}

const cartItems = `-- name: CartItems :many
SELECT ci.id, ci.variant_id, p.id AS product_id, p.slug, p.name, v.option_values,
       (p.base_price + v.price_delta)::int AS unit_price, ci.quantity, v.stock,
       (p.is_visible AND v.is_visible AND v.stock >= ci.quantity)::boolean AS sellable
FROM cart_items ci
JOIN carts c            ON c.id = ci.cart_id
JOIN product_variants v ON v.id = ci.variant_id
JOIN products p         ON p.id = v.product_id
WHERE ($1::uuid IS NOT NULL AND c.user_id = $1)
   OR ($2::text IS NOT NULL AND c.guest_key = $2)
ORDER BY ci.created_at, ci.id
`

type CartItemsParams struct {
	UserID   *string
	GuestKey *string
}

type CartItemsRow struct {
	ID           string
	VariantID    string
	ProductID    string
	Slug         string
	Name         string
	OptionValues []byte
	UnitPrice    int32
	Quantity     int32
	Stock        int32
	Sellable     bool
}

func (q *Queries) CartItems(ctx context.Context, arg CartItemsParams) ([]CartItemsRow, error) {
	rows, err := q.db.Query(ctx, cartItems, arg.UserID, arg.GuestKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItemsRow{}
	for rows.Next() {
		var i CartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.ProductID,
			&i.Slug,
			&i.Name,
			&i.OptionValues,
			&i.UnitPrice,
			&i.Quantity,
			&i.Stock,
			&i.Sellable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items ci WHERE ci.id = $1 AND
    ci.cart_id IN (SELECT id FROM carts
                   WHERE ($2::uuid IS NOT NULL AND user_id = $2)
                      OR ($3::text IS NOT NULL AND guest_key = $3))
`

type DeleteCartItemParams struct {
	ID       string
	UserID   *string
	GuestKey *string
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.UserID, arg.GuestKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const guestCartID = `-- name: GuestCartID :one
SELECT id FROM carts WHERE guest_key = $1
`

func (q *Queries) GuestCartID(ctx context.Context, guestKey *string) (string, error) {
	row := q.db.QueryRow(ctx, guestCartID, guestKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const mergePlan = `-- name: MergePlan :many
SELECT gi.variant_id, gi.quantity AS guest_quantity, COALESCE(mi.quantity, 0)::int AS member_quantity, v.stock
FROM cart_items gi
JOIN product_variants v ON v.id = gi.variant_id
LEFT JOIN cart_items mi ON mi.cart_id = $1 AND mi.variant_id = gi.variant_id
WHERE gi.cart_id = $2
`

type MergePlanParams struct {
	MemberCart string
	GuestCart  string
}

type MergePlanRow struct {
	VariantID      string
	GuestQuantity  int32
	MemberQuantity int32
	Stock          int32
}

func (q *Queries) MergePlan(ctx context.Context, arg MergePlanParams) ([]MergePlanRow, error) {
	rows, err := q.db.Query(ctx, mergePlan, arg.MemberCart, arg.GuestCart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MergePlanRow{}
	for rows.Next() {
		var i MergePlanRow
		if err := rows.Scan(
			&i.VariantID,
			&i.GuestQuantity,
			&i.MemberQuantity,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCartItemQuantity = `-- name: SetCartItemQuantity :execrows
UPDATE cart_items ci SET quantity = $1, updated_at = now()
WHERE ci.id = $2 AND
    ci.cart_id IN (SELECT id FROM carts
                   WHERE ($3::uuid IS NOT NULL AND user_id = $3)
                      OR ($4::text IS NOT NULL AND guest_key = $4))
`

type SetCartItemQuantityParams struct {
	Quantity int32
	ID       string
	UserID   *string
	GuestKey *string
}

func (q *Queries) SetCartItemQuantity(ctx context.Context, arg SetCartItemQuantityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCartItemQuantity,
		arg.Quantity,
		arg.ID,
		arg.UserID,
		arg.GuestKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCartItem = `-- name: UpsertCartItem :exec
INSERT INTO cart_items (cart_id, variant_id, quantity) VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id)
DO UPDATE SET quantity = $3, updated_at = now()
`

type UpsertCartItemParams struct {
	CartID    string
	VariantID string
	Quantity  int32
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) error {
	_, err := q.db.Exec(ctx, upsertCartItem, arg.CartID, arg.VariantID, arg.Quantity)
	return err
}
