// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image.sql

package commerceq

import (
	"context"
	"time"
)

const countProductImages = `-- name: CountProductImages :one

SELECT count(*) FROM product_images WHERE product_id = $1
`

// 상품 이미지 (image.go, A-502 · P-306). 파일은 업로드 루트에 있고 이 표는 경로를 갖는다.
func (q *Queries) CountProductImages(ctx context.Context, productID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductImages, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, stored_path, original_name, mime_type, byte_size)
VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at
`

type CreateProductImageParams struct {
	ProductID    string
	StoredPath   string
	OriginalName string
	MimeType     string
	ByteSize     int64
}

type CreateProductImageRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (CreateProductImageRow, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.StoredPath,
		arg.OriginalName,
		arg.MimeType,
		arg.ByteSize,
	)
	var i CreateProductImageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :one
DELETE FROM product_images WHERE id = $1 RETURNING product_id, stored_path
`

type DeleteProductImageRow struct {
	ProductID  string
	StoredPath string
}

// 지우면서 경로를 받는다. 읽고 나서 지우면 그 사이에 행이 사라질 수 있다.
func (q *Queries) DeleteProductImage(ctx context.Context, id string) (DeleteProductImageRow, error) {
	row := q.db.QueryRow(ctx, deleteProductImage, id)
	var i DeleteProductImageRow
	err := row.Scan(&i.ProductID, &i.StoredPath)
	return i, err
}

const productImageByID = `-- name: ProductImageByID :one
SELECT i.id, i.product_id, i.stored_path, i.original_name, i.mime_type, i.byte_size, i.created_at,
       p.is_visible AS product_visible
FROM product_images i JOIN products p ON p.id = i.product_id
WHERE i.id = $1
`

type ProductImageByIDRow struct {
	ID             string
	ProductID      string
	StoredPath     string
	OriginalName   string
	MimeType       string
	ByteSize       int64
	CreatedAt      time.Time
	ProductVisible bool
}

// 상품의 노출 여부를 **같은 문장으로** 낸다. 따로 읽으면 한쪽만 확인하는 호출자가 생긴다.
func (q *Queries) ProductImageByID(ctx context.Context, id string) (ProductImageByIDRow, error) {
	row := q.db.QueryRow(ctx, productImageByID, id)
	var i ProductImageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StoredPath,
		&i.OriginalName,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
		&i.ProductVisible,
	)
	return i, err
}

const productImagePaths = `-- name: ProductImagePaths :many
SELECT stored_path FROM product_images WHERE product_id = $1
`

func (q *Queries) ProductImagePaths(ctx context.Context, productID string) ([]string, error) {
	rows, err := q.db.Query(ctx, productImagePaths, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var stored_path string
		if err := rows.Scan(&stored_path); err != nil {
			return nil, err
		}
		items = append(items, stored_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productImages = `-- name: ProductImages :many
SELECT id, product_id, stored_path, original_name, mime_type, byte_size, created_at
FROM product_images WHERE product_id = $1 ORDER BY created_at, id
`

// 올린 순서다. 첫 행이 대표 이미지다 (ListProducts 의 image_id 와 같은 정렬).
func (q *Queries) ProductImages(ctx context.Context, productID string) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, productImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoredPath,
			&i.OriginalName,
			&i.MimeType,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
