// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package commerceq

import (
	"time"
)

type ProductImage struct {
	ID           string
	ProductID    string
	StoredPath   string
	OriginalName string
	MimeType     string
	ByteSize     int64
	CreatedAt    time.Time
}

type Term struct {
	ID          string
	Kind        string
	Version     string
	Body        string
	EffectiveAt time.Time
	IsRequired  bool
	CreatedAt   time.Time
}
