// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package commerceq

import (
	"context"
)

const openOrders = `-- name: OpenOrders :one
SELECT count(*) FROM orders WHERE status <> ALL($1::text[])
`

func (q *Queries) OpenOrders(ctx context.Context, terminal []string) (int64, error) {
	row := q.db.QueryRow(ctx, openOrders, terminal)
	var count int64
	err := row.Scan(&count)
	return count, err
}
