// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package commerceq

import (
	"context"
	"time"
)

const declinePayment = `-- name: DeclinePayment :exec
UPDATE payments SET status = '실패', raw_response = $2, updated_at = now()
WHERE id = $1
`

type DeclinePaymentParams struct {
	ID          string
	RawResponse []byte
}

func (q *Queries) DeclinePayment(ctx context.Context, arg DeclinePaymentParams) error {
	_, err := q.db.Exec(ctx, declinePayment, arg.ID, arg.RawResponse)
	return err
}

const failPaymentByID = `-- name: FailPaymentByID :exec
UPDATE payments SET status = '실패', updated_at = now() WHERE id = $1
`

func (q *Queries) FailPaymentByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, failPaymentByID, id)
	return err
}

const failPendingPayment = `-- name: FailPendingPayment :execrows
UPDATE payments SET status = '실패', updated_at = now()
WHERE order_id = (SELECT id FROM orders WHERE order_no = $1)
  AND kind = '주문결제' AND status = '대기'
`

func (q *Queries) FailPendingPayment(ctx context.Context, orderNo string) (int64, error) {
	result, err := q.db.Exec(ctx, failPendingPayment, orderNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockOrderForPayment = `-- name: LockOrderForPayment :one

SELECT id, status, total_amount, created_at FROM orders
WHERE order_no = $1 FOR UPDATE
`

type LockOrderForPaymentRow struct {
	ID          string
	Status      string
	TotalAmount int32
	CreatedAt   time.Time
}

// 결제 (payment.go, FR-607/FR-608). 선점은 부분 유니크가, 전이는 비교-교환이 막는다.
func (q *Queries) LockOrderForPayment(ctx context.Context, orderNo string) (LockOrderForPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockOrderForPayment, orderNo)
	var i LockOrderForPaymentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const recordPaymentResult = `-- name: RecordPaymentResult :exec
UPDATE payments SET status = $1,
       approved_at = CASE WHEN $1 = '승인' THEN now() ELSE approved_at END,
       raw_response = $2, secret = NULLIF($3::text, ''), updated_at = now()
WHERE id = $4
`

type RecordPaymentResultParams struct {
	Status      string
	RawResponse []byte
	Secret      string
	ID          string
}

func (q *Queries) RecordPaymentResult(ctx context.Context, arg RecordPaymentResultParams) error {
	_, err := q.db.Exec(ctx, recordPaymentResult,
		arg.Status,
		arg.RawResponse,
		arg.Secret,
		arg.ID,
	)
	return err
}

const reservePayment = `-- name: ReservePayment :one
INSERT INTO payments (order_id, kind, status, pg, payment_key, approved_amount)
VALUES ($1, '주문결제', '대기', $2, $3, $4) RETURNING id
`

type ReservePaymentParams struct {
	OrderID        string
	Pg             string
	PaymentKey     string
	ApprovedAmount int32
}

func (q *Queries) ReservePayment(ctx context.Context, arg ReservePaymentParams) (string, error) {
	row := q.db.QueryRow(ctx, reservePayment,
		arg.OrderID,
		arg.Pg,
		arg.PaymentKey,
		arg.ApprovedAmount,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
