// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_admin.sql

package commerceq

import (
	"context"
)

const addVariant = `-- name: AddVariant :one
INSERT INTO product_variants (product_id, option_values, price_delta, stock, sku)
VALUES ($1, $2, $3, 0, NULLIF($4::text, '')) RETURNING id
`

type AddVariantParams struct {
	ProductID    string
	OptionValues []byte
	PriceDelta   int32
	Sku          string
}

func (q *Queries) AddVariant(ctx context.Context, arg AddVariantParams) (string, error) {
	row := q.db.QueryRow(ctx, addVariant,
		arg.ProductID,
		arg.OptionValues,
		arg.PriceDelta,
		arg.Sku,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductOptions = `-- name: DeleteProductOptions :exec
DELETE FROM product_options WHERE product_id = $1
`

func (q *Queries) DeleteProductOptions(ctx context.Context, productID string) error {
	_, err := q.db.Exec(ctx, deleteProductOptions, productID)
	return err
}

const editVariant = `-- name: EditVariant :execrows
UPDATE product_variants
SET stock = stock + $3, sku = NULLIF($4::text, ''), price_delta = $5, updated_at = now()
WHERE id = $1 AND product_id = $2
`

type EditVariantParams struct {
	ID         string
	ProductID  string
	Stock      int32
	Column4    string
	PriceDelta int32
}

func (q *Queries) EditVariant(ctx context.Context, arg EditVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, editVariant,
		arg.ID,
		arg.ProductID,
		arg.Stock,
		arg.Column4,
		arg.PriceDelta,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProductOption = `-- name: InsertProductOption :exec
INSERT INTO product_options (product_id, name, values, sort_order)
VALUES ($1, $2, $3, $4)
`

type InsertProductOptionParams struct {
	ProductID string
	Name      string
	Values    []byte
	SortOrder int32
}

func (q *Queries) InsertProductOption(ctx context.Context, arg InsertProductOptionParams) error {
	_, err := q.db.Exec(ctx, insertProductOption,
		arg.ProductID,
		arg.Name,
		arg.Values,
		arg.SortOrder,
	)
	return err
}

const insertVariantIfMissing = `-- name: InsertVariantIfMissing :exec
INSERT INTO product_variants (product_id, option_values, price_delta, stock)
VALUES ($1, $2, 0, 0)
ON CONFLICT (product_id, option_values) DO NOTHING
`

type InsertVariantIfMissingParams struct {
	ProductID    string
	OptionValues []byte
}

func (q *Queries) InsertVariantIfMissing(ctx context.Context, arg InsertVariantIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertVariantIfMissing, arg.ProductID, arg.OptionValues)
	return err
}

const lockVariantOfProduct = `-- name: LockVariantOfProduct :one
SELECT stock FROM product_variants WHERE id = $1 AND product_id = $2 FOR UPDATE
`

type LockVariantOfProductParams struct {
	ID        string
	ProductID string
}

func (q *Queries) LockVariantOfProduct(ctx context.Context, arg LockVariantOfProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockVariantOfProduct, arg.ID, arg.ProductID)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const options = `-- name: Options :many
SELECT name, values FROM product_options
WHERE product_id = $1 ORDER BY sort_order, name
`

type OptionsRow struct {
	Name   string
	Values []byte
}

func (q *Queries) Options(ctx context.Context, productID string) ([]OptionsRow, error) {
	rows, err := q.db.Query(ctx, options, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionsRow{}
	for rows.Next() {
		var i OptionsRow
		if err := rows.Scan(&i.Name, &i.Values); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productByID = `-- name: ProductByID :one

SELECT id, slug, name, description, base_price, is_visible
FROM products WHERE id = $1
`

type ProductByIDRow struct {
	ID          string
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
}

// 상품 관리 (product_admin.go, A-502/A-503). 재고는 조정값으로만 움직인다.
func (q *Queries) ProductByID(ctx context.Context, id string) (ProductByIDRow, error) {
	row := q.db.QueryRow(ctx, productByID, id)
	var i ProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.IsVisible,
	)
	return i, err
}

const productExists = `-- name: ProductExists :one
SELECT true::boolean AS found FROM products WHERE id = $1
`

func (q *Queries) ProductExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE products SET slug = $2, name = $3, description = $4,
       base_price = $5, is_visible = $6, updated_at = now()
WHERE id = $1
`

type UpdateProductParams struct {
	ID          string
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.IsVisible,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
