// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refund.sql

package commerceq

import (
	"context"
	"time"
)

const approvedPaymentAmounts = `-- name: ApprovedPaymentAmounts :one
SELECT approved_amount, refunded_amount FROM payments
WHERE order_id = $1 AND kind = '주문결제' AND status = '승인'
`

type ApprovedPaymentAmountsRow struct {
	ApprovedAmount int32
	RefundedAmount int32
}

func (q *Queries) ApprovedPaymentAmounts(ctx context.Context, orderID string) (ApprovedPaymentAmountsRow, error) {
	row := q.db.QueryRow(ctx, approvedPaymentAmounts, orderID)
	var i ApprovedPaymentAmountsRow
	err := row.Scan(&i.ApprovedAmount, &i.RefundedAmount)
	return i, err
}

const approvedPaymentForOrderNo = `-- name: ApprovedPaymentForOrderNo :one

SELECT o.id AS order_id, p.id AS payment_id FROM orders o
JOIN payments p ON p.order_id = o.id AND p.kind = '주문결제' AND p.status = '승인'
WHERE o.order_no = $1
`

type ApprovedPaymentForOrderNoRow struct {
	OrderID   string
	PaymentID string
}

// 환불·취소 (refund.go, FR-611/FR-625). 한도는 DB CHECK 가, 중복은 request_key 유니크가 막는다.
func (q *Queries) ApprovedPaymentForOrderNo(ctx context.Context, orderNo string) (ApprovedPaymentForOrderNoRow, error) {
	row := q.db.QueryRow(ctx, approvedPaymentForOrderNo, orderNo)
	var i ApprovedPaymentForOrderNoRow
	err := row.Scan(&i.OrderID, &i.PaymentID)
	return i, err
}

const completeRefund = `-- name: CompleteRefund :execrows
UPDATE refunds SET status = '완료', pg_response = $1, updated_at = now()
WHERE id = $2 AND status = '승인'
`

type CompleteRefundParams struct {
	PgResponse []byte
	ID         string
}

func (q *Queries) CompleteRefund(ctx context.Context, arg CompleteRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRefund, arg.PgResponse, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCancelRefund = `-- name: InsertCancelRefund :one
INSERT INTO refunds (order_id, payment_id, status, requester, amount, reason, request_key)
VALUES ($1, $2, '요청', $3, $4, '주문 취소', $5) RETURNING id
`

type InsertCancelRefundParams struct {
	OrderID    string
	PaymentID  string
	Requester  string
	Amount     int32
	RequestKey string
}

func (q *Queries) InsertCancelRefund(ctx context.Context, arg InsertCancelRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCancelRefund,
		arg.OrderID,
		arg.PaymentID,
		arg.Requester,
		arg.Amount,
		arg.RequestKey,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (order_id, payment_id, status, requester, amount, reason, request_key)
VALUES ($1, $2, '요청', $3, $4, $5, $6) RETURNING id
`

type InsertRefundParams struct {
	OrderID    string
	PaymentID  string
	Requester  string
	Amount     int32
	Reason     string
	RequestKey string
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.OrderID,
		arg.PaymentID,
		arg.Requester,
		arg.Amount,
		arg.Reason,
		arg.RequestKey,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertRefundItem = `-- name: InsertRefundItem :exec
INSERT INTO refund_items (refund_id, order_item_id, quantity) VALUES ($1,$2,$3)
`

type InsertRefundItemParams struct {
	RefundID    string
	OrderItemID string
	Quantity    int32
}

func (q *Queries) InsertRefundItem(ctx context.Context, arg InsertRefundItemParams) error {
	_, err := q.db.Exec(ctx, insertRefundItem, arg.RefundID, arg.OrderItemID, arg.Quantity)
	return err
}

const lockApprovedPayment = `-- name: LockApprovedPayment :one
SELECT id, approved_amount, refunded_amount FROM payments
WHERE order_id = $1 AND kind = '주문결제' AND status = '승인' FOR UPDATE
`

type LockApprovedPaymentRow struct {
	ID             string
	ApprovedAmount int32
	RefundedAmount int32
}

func (q *Queries) LockApprovedPayment(ctx context.Context, orderID string) (LockApprovedPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockApprovedPayment, orderID)
	var i LockApprovedPaymentRow
	err := row.Scan(&i.ID, &i.ApprovedAmount, &i.RefundedAmount)
	return i, err
}

const lockOrderForCancel = `-- name: LockOrderForCancel :one
SELECT id, status, total_amount FROM orders WHERE order_no = $1 FOR UPDATE
`

type LockOrderForCancelRow struct {
	ID          string
	Status      string
	TotalAmount int32
}

func (q *Queries) LockOrderForCancel(ctx context.Context, orderNo string) (LockOrderForCancelRow, error) {
	row := q.db.QueryRow(ctx, lockOrderForCancel, orderNo)
	var i LockOrderForCancelRow
	err := row.Scan(&i.ID, &i.Status, &i.TotalAmount)
	return i, err
}

const lockOrderItemForRefund = `-- name: LockOrderItemForRefund :one
SELECT line_amount::int AS line_amount, discount_amount, quantity, settled_quantity
FROM order_items WHERE id = $1 AND order_id = $2 FOR UPDATE
`

type LockOrderItemForRefundParams struct {
	ID      string
	OrderID string
}

type LockOrderItemForRefundRow struct {
	LineAmount      int32
	DiscountAmount  int32
	Quantity        int32
	SettledQuantity int32
}

func (q *Queries) LockOrderItemForRefund(ctx context.Context, arg LockOrderItemForRefundParams) (LockOrderItemForRefundRow, error) {
	row := q.db.QueryRow(ctx, lockOrderItemForRefund, arg.ID, arg.OrderID)
	var i LockOrderItemForRefundRow
	err := row.Scan(
		&i.LineAmount,
		&i.DiscountAmount,
		&i.Quantity,
		&i.SettledQuantity,
	)
	return i, err
}

const lockRefundForExecute = `-- name: LockRefundForExecute :one
SELECT r.status, r.reason, r.request_key, r.amount, p.payment_key
FROM refunds r JOIN payments p ON p.id = r.payment_id
WHERE r.id = $1 FOR UPDATE
`

type LockRefundForExecuteRow struct {
	Status     string
	Reason     string
	RequestKey string
	Amount     int32
	PaymentKey string
}

func (q *Queries) LockRefundForExecute(ctx context.Context, id string) (LockRefundForExecuteRow, error) {
	row := q.db.QueryRow(ctx, lockRefundForExecute, id)
	var i LockRefundForExecuteRow
	err := row.Scan(
		&i.Status,
		&i.Reason,
		&i.RequestKey,
		&i.Amount,
		&i.PaymentKey,
	)
	return i, err
}

const markRefundExecuting = `-- name: MarkRefundExecuting :exec
UPDATE refunds SET status = '승인', updated_at = now() WHERE id = $1 AND status = '요청'
`

func (q *Queries) MarkRefundExecuting(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRefundExecuting, id)
	return err
}

const openReturnItemCount = `-- name: OpenReturnItemCount :one
SELECT count(*) FROM return_items WHERE order_item_id = $1 AND is_open
`

func (q *Queries) OpenReturnItemCount(ctx context.Context, orderItemID string) (int64, error) {
	row := q.db.QueryRow(ctx, openReturnItemCount, orderItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const orderItemStock = `-- name: OrderItemStock :many
SELECT variant_id, quantity FROM order_items WHERE order_id = $1
`

type OrderItemStockRow struct {
	VariantID string
	Quantity  int32
}

func (q *Queries) OrderItemStock(ctx context.Context, orderID string) ([]OrderItemStockRow, error) {
	rows, err := q.db.Query(ctx, orderItemStock, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemStockRow{}
	for rows.Next() {
		var i OrderItemStockRow
		if err := rows.Scan(&i.VariantID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundForReturn = `-- name: RefundForReturn :one
SELECT rf.id FROM refunds rf
JOIN returns rt ON rt.id = rf.return_id
JOIN orders o ON o.id = rf.order_id
WHERE o.order_no = $1 AND rt.return_no = $2
ORDER BY rf.created_at DESC LIMIT 1
`

type RefundForReturnParams struct {
	OrderNo  string
	ReturnNo string
}

func (q *Queries) RefundForReturn(ctx context.Context, arg RefundForReturnParams) (string, error) {
	row := q.db.QueryRow(ctx, refundForReturn, arg.OrderNo, arg.ReturnNo)
	var id string
	err := row.Scan(&id)
	return id, err
}

const refundedTotal = `-- name: RefundedTotal :one
SELECT p.approved_amount, p.refunded_amount FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.order_no = $1 AND p.kind = '주문결제' AND p.status = '승인'
`

type RefundedTotalRow struct {
	ApprovedAmount int32
	RefundedAmount int32
}

func (q *Queries) RefundedTotal(ctx context.Context, orderNo string) (RefundedTotalRow, error) {
	row := q.db.QueryRow(ctx, refundedTotal, orderNo)
	var i RefundedTotalRow
	err := row.Scan(&i.ApprovedAmount, &i.RefundedAmount)
	return i, err
}

const refunds = `-- name: Refunds :many
SELECT id, status, requester, amount, reason, created_at FROM refunds
WHERE order_id = $1 ORDER BY created_at DESC, id
`

type RefundsRow struct {
	ID        string
	Status    string
	Requester string
	Amount    int32
	Reason    string
	CreatedAt time.Time
}

func (q *Queries) Refunds(ctx context.Context, orderID string) ([]RefundsRow, error) {
	rows, err := q.db.Query(ctx, refunds, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundsRow{}
	for rows.Next() {
		var i RefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Requester,
			&i.Amount,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRefund = `-- name: RejectRefund :one
UPDATE refunds SET status = '거부', reason = $2, updated_at = now()
WHERE id = $1 AND status = '요청' RETURNING payment_id, amount
`

type RejectRefundParams struct {
	ID     string
	Reason string
}

type RejectRefundRow struct {
	PaymentID string
	Amount    int32
}

func (q *Queries) RejectRefund(ctx context.Context, arg RejectRefundParams) (RejectRefundRow, error) {
	row := q.db.QueryRow(ctx, rejectRefund, arg.ID, arg.Reason)
	var i RejectRefundRow
	err := row.Scan(&i.PaymentID, &i.Amount)
	return i, err
}

const releaseRefundAmount = `-- name: ReleaseRefundAmount :exec
UPDATE payments SET refunded_amount = refunded_amount - $1, updated_at = now()
WHERE id = $2
`

type ReleaseRefundAmountParams struct {
	Amount int32
	ID     string
}

func (q *Queries) ReleaseRefundAmount(ctx context.Context, arg ReleaseRefundAmountParams) error {
	_, err := q.db.Exec(ctx, releaseRefundAmount, arg.Amount, arg.ID)
	return err
}

const reserveRefundAmount = `-- name: ReserveRefundAmount :exec
UPDATE payments SET refunded_amount = refunded_amount + $1, updated_at = now()
WHERE id = $2
`

type ReserveRefundAmountParams struct {
	Amount int32
	ID     string
}

func (q *Queries) ReserveRefundAmount(ctx context.Context, arg ReserveRefundAmountParams) error {
	_, err := q.db.Exec(ctx, reserveRefundAmount, arg.Amount, arg.ID)
	return err
}

const revertRefundToRequested = `-- name: RevertRefundToRequested :exec
UPDATE refunds SET status = '요청', updated_at = now() WHERE id = $1 AND status = '승인'
`

func (q *Queries) RevertRefundToRequested(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revertRefundToRequested, id)
	return err
}

const settleAllOrderItems = `-- name: SettleAllOrderItems :exec
UPDATE order_items SET settled_quantity = quantity, updated_at = now()
WHERE order_id = $1
`

func (q *Queries) SettleAllOrderItems(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, settleAllOrderItems, orderID)
	return err
}

const settleOrderItem = `-- name: SettleOrderItem :exec
UPDATE order_items SET settled_quantity = settled_quantity + $1, updated_at = now()
WHERE id = $2
`

type SettleOrderItemParams struct {
	Quantity int32
	ID       string
}

func (q *Queries) SettleOrderItem(ctx context.Context, arg SettleOrderItemParams) error {
	_, err := q.db.Exec(ctx, settleOrderItem, arg.Quantity, arg.ID)
	return err
}

const unsettleRefundItems = `-- name: UnsettleRefundItems :exec
UPDATE order_items oi SET settled_quantity = oi.settled_quantity - ri.quantity,
                          updated_at = now()
FROM refund_items ri
WHERE ri.refund_id = $1 AND oi.id = ri.order_item_id
`

func (q *Queries) UnsettleRefundItems(ctx context.Context, refundID string) error {
	_, err := q.db.Exec(ctx, unsettleRefundItems, refundID)
	return err
}
