// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: returns.sql

package commerceq

import (
	"context"
	"time"
)

const approveExchangePayment = `-- name: ApproveExchangePayment :exec
UPDATE payments SET status = $1, approved_at = now(), raw_response = $2,
       secret = NULLIF($3::text, ''), updated_at = now()
WHERE id = $4
`

type ApproveExchangePaymentParams struct {
	Status      string
	RawResponse []byte
	Secret      string
	ID          string
}

func (q *Queries) ApproveExchangePayment(ctx context.Context, arg ApproveExchangePaymentParams) error {
	_, err := q.db.Exec(ctx, approveExchangePayment,
		arg.Status,
		arg.RawResponse,
		arg.Secret,
		arg.ID,
	)
	return err
}

const approvedPaymentID = `-- name: ApprovedPaymentID :one
SELECT id FROM payments
WHERE order_id = $1 AND kind = '주문결제' AND status = '승인'
`

func (q *Queries) ApprovedPaymentID(ctx context.Context, orderID string) (string, error) {
	row := q.db.QueryRow(ctx, approvedPaymentID, orderID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const closeReturnItems = `-- name: CloseReturnItems :exec
UPDATE return_items SET is_open = false, updated_at = now() WHERE return_id = $1
`

func (q *Queries) CloseReturnItems(ctx context.Context, returnID string) error {
	_, err := q.db.Exec(ctx, closeReturnItems, returnID)
	return err
}

const closeReturnItemsNoTouch = `-- name: CloseReturnItemsNoTouch :exec
UPDATE return_items SET is_open = false WHERE return_id = $1
`

func (q *Queries) CloseReturnItemsNoTouch(ctx context.Context, returnID string) error {
	_, err := q.db.Exec(ctx, closeReturnItemsNoTouch, returnID)
	return err
}

const exchangeDiffDue = `-- name: ExchangeDiffDue :one
SELECT r.id, r.return_no, r.order_id, r.status, COALESCE(r.price_difference, 0)::int AS price_difference
FROM returns r JOIN orders o ON o.id = r.order_id
WHERE r.return_no = $1 AND o.order_no = $2 AND r.kind = '교환'
  AND ($3::text = '' OR o.user_id::text = $3)
`

type ExchangeDiffDueParams struct {
	ReturnNo string
	OrderNo  string
	UserID   string
}

type ExchangeDiffDueRow struct {
	ID              string
	ReturnNo        string
	OrderID         string
	Status          string
	PriceDifference int32
}

func (q *Queries) ExchangeDiffDue(ctx context.Context, arg ExchangeDiffDueParams) (ExchangeDiffDueRow, error) {
	row := q.db.QueryRow(ctx, exchangeDiffDue, arg.ReturnNo, arg.OrderNo, arg.UserID)
	var i ExchangeDiffDueRow
	err := row.Scan(
		&i.ID,
		&i.ReturnNo,
		&i.OrderID,
		&i.Status,
		&i.PriceDifference,
	)
	return i, err
}

const exchangeTarget = `-- name: ExchangeTarget :one
SELECT v.product_id, v.price_delta FROM product_variants v
JOIN products p ON p.id = v.product_id
WHERE v.id = $1 AND v.is_visible AND p.is_visible
`

type ExchangeTargetRow struct {
	ProductID  string
	PriceDelta int32
}

func (q *Queries) ExchangeTarget(ctx context.Context, id string) (ExchangeTargetRow, error) {
	row := q.db.QueryRow(ctx, exchangeTarget, id)
	var i ExchangeTargetRow
	err := row.Scan(&i.ProductID, &i.PriceDelta)
	return i, err
}

const insertReturn = `-- name: InsertReturn :one
INSERT INTO returns (return_no, order_id, kind, status, reason,
                     new_variant_id, price_difference)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id
`

type InsertReturnParams struct {
	ReturnNo        string
	OrderID         string
	Kind            string
	Status          string
	Reason          string
	NewVariantID    *string
	PriceDifference *int32
}

func (q *Queries) InsertReturn(ctx context.Context, arg InsertReturnParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReturn,
		arg.ReturnNo,
		arg.OrderID,
		arg.Kind,
		arg.Status,
		arg.Reason,
		arg.NewVariantID,
		arg.PriceDifference,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertReturnItem = `-- name: InsertReturnItem :exec
INSERT INTO return_items (return_id, order_item_id, quantity) VALUES ($1,$2,$3)
`

type InsertReturnItemParams struct {
	ReturnID    string
	OrderItemID string
	Quantity    int32
}

func (q *Queries) InsertReturnItem(ctx context.Context, arg InsertReturnItemParams) error {
	_, err := q.db.Exec(ctx, insertReturnItem, arg.ReturnID, arg.OrderItemID, arg.Quantity)
	return err
}

const insertReturnRefund = `-- name: InsertReturnRefund :one
INSERT INTO refunds (order_id, payment_id, return_id, status, requester,
                     amount, reason, request_key)
VALUES ($1,$2,$3,'요청','관리자',$4,'반품 환불',$5) RETURNING id
`

type InsertReturnRefundParams struct {
	OrderID    string
	PaymentID  string
	ReturnID   *string
	Amount     int32
	RequestKey string
}

func (q *Queries) InsertReturnRefund(ctx context.Context, arg InsertReturnRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReturnRefund,
		arg.OrderID,
		arg.PaymentID,
		arg.ReturnID,
		arg.Amount,
		arg.RequestKey,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockOrderItemForReturn = `-- name: LockOrderItemForReturn :one
SELECT oi.product_id, oi.quantity, oi.settled_quantity, v.price_delta
FROM order_items oi JOIN product_variants v ON v.id = oi.variant_id
WHERE oi.id = $1 AND oi.order_id = $2 FOR UPDATE OF oi
`

type LockOrderItemForReturnParams struct {
	ID      string
	OrderID string
}

type LockOrderItemForReturnRow struct {
	ProductID       string
	Quantity        int32
	SettledQuantity int32
	PriceDelta      int32
}

func (q *Queries) LockOrderItemForReturn(ctx context.Context, arg LockOrderItemForReturnParams) (LockOrderItemForReturnRow, error) {
	row := q.db.QueryRow(ctx, lockOrderItemForReturn, arg.ID, arg.OrderID)
	var i LockOrderItemForReturnRow
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.SettledQuantity,
		&i.PriceDelta,
	)
	return i, err
}

const lockReturnForExchange = `-- name: LockReturnForExchange :one
SELECT r.id, r.kind, r.status, r.order_id, COALESCE(r.price_difference, 0)::int AS price_difference
FROM returns r JOIN orders o ON o.id = r.order_id
WHERE r.return_no = $1 AND o.order_no = $2 FOR UPDATE OF r
`

type LockReturnForExchangeParams struct {
	ReturnNo string
	OrderNo  string
}

type LockReturnForExchangeRow struct {
	ID              string
	Kind            string
	Status          string
	OrderID         string
	PriceDifference int32
}

func (q *Queries) LockReturnForExchange(ctx context.Context, arg LockReturnForExchangeParams) (LockReturnForExchangeRow, error) {
	row := q.db.QueryRow(ctx, lockReturnForExchange, arg.ReturnNo, arg.OrderNo)
	var i LockReturnForExchangeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OrderID,
		&i.PriceDifference,
	)
	return i, err
}

const lockReturnForPickup = `-- name: LockReturnForPickup :one
SELECT r.id, r.kind, r.status, r.order_id FROM returns r
JOIN orders o ON o.id = r.order_id
WHERE r.return_no = $1 AND o.order_no = $2 FOR UPDATE OF r
`

type LockReturnForPickupParams struct {
	ReturnNo string
	OrderNo  string
}

type LockReturnForPickupRow struct {
	ID      string
	Kind    string
	Status  string
	OrderID string
}

func (q *Queries) LockReturnForPickup(ctx context.Context, arg LockReturnForPickupParams) (LockReturnForPickupRow, error) {
	row := q.db.QueryRow(ctx, lockReturnForPickup, arg.ReturnNo, arg.OrderNo)
	var i LockReturnForPickupRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OrderID,
	)
	return i, err
}

const lockReturnForReject = `-- name: LockReturnForReject :one
SELECT r.id, r.kind, r.status, r.order_id, COALESCE(r.new_variant_id::text, '')::text AS new_variant_id
FROM returns r JOIN orders o ON o.id = r.order_id
WHERE r.return_no = $1 AND o.order_no = $2 FOR UPDATE OF r
`

type LockReturnForRejectParams struct {
	ReturnNo string
	OrderNo  string
}

type LockReturnForRejectRow struct {
	ID           string
	Kind         string
	Status       string
	OrderID      string
	NewVariantID string
}

func (q *Queries) LockReturnForReject(ctx context.Context, arg LockReturnForRejectParams) (LockReturnForRejectRow, error) {
	row := q.db.QueryRow(ctx, lockReturnForReject, arg.ReturnNo, arg.OrderNo)
	var i LockReturnForRejectRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OrderID,
		&i.NewVariantID,
	)
	return i, err
}

const lockReturnForSettle = `-- name: LockReturnForSettle :one
SELECT r.id, r.kind, r.status, r.order_id,
       COALESCE(r.shipping_fee_policy, '')::text AS fee_policy, COALESCE(r.shipping_fee_amount, 0)::int AS fee_amount
FROM returns r JOIN orders o ON o.id = r.order_id
WHERE r.return_no = $1 AND o.order_no = $2 FOR UPDATE OF r
`

type LockReturnForSettleParams struct {
	ReturnNo string
	OrderNo  string
}

type LockReturnForSettleRow struct {
	ID        string
	Kind      string
	Status    string
	OrderID   string
	FeePolicy string
	FeeAmount int32
}

func (q *Queries) LockReturnForSettle(ctx context.Context, arg LockReturnForSettleParams) (LockReturnForSettleRow, error) {
	row := q.db.QueryRow(ctx, lockReturnForSettle, arg.ReturnNo, arg.OrderNo)
	var i LockReturnForSettleRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OrderID,
		&i.FeePolicy,
		&i.FeeAmount,
	)
	return i, err
}

const lockReturnGross = `-- name: LockReturnGross :many
SELECT ri.order_item_id, ri.quantity AS return_quantity,
       oi.line_amount::int AS line_amount, oi.discount_amount, oi.quantity, oi.settled_quantity
FROM return_items ri
JOIN order_items oi ON oi.id = ri.order_item_id
WHERE ri.return_id = $1 AND ri.is_open
ORDER BY ri.order_item_id
FOR UPDATE OF oi
`

type LockReturnGrossRow struct {
	OrderItemID     string
	ReturnQuantity  int32
	LineAmount      int32
	DiscountAmount  int32
	Quantity        int32
	SettledQuantity int32
}

func (q *Queries) LockReturnGross(ctx context.Context, returnID string) ([]LockReturnGrossRow, error) {
	rows, err := q.db.Query(ctx, lockReturnGross, returnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockReturnGrossRow{}
	for rows.Next() {
		var i LockReturnGrossRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.ReturnQuantity,
			&i.LineAmount,
			&i.DiscountAmount,
			&i.Quantity,
			&i.SettledQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveReturnStatus = `-- name: MoveReturnStatus :execrows
UPDATE returns SET status = $1, updated_at = now()
WHERE id = $2 AND status = $3
`

type MoveReturnStatusParams struct {
	ToStatus   string
	ID         string
	FromStatus string
}

func (q *Queries) MoveReturnStatus(ctx context.Context, arg MoveReturnStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveReturnStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPickup = `-- name: RecordPickup :exec
UPDATE returns SET status = $1, fault = $2,
       shipping_fee_policy = $3, shipping_fee_amount = $4, updated_at = now()
WHERE id = $5 AND status = $6
`

type RecordPickupParams struct {
	Status     string
	Fault      *string
	FeePolicy  *string
	FeeAmount  *int32
	ID         string
	FromStatus string
}

func (q *Queries) RecordPickup(ctx context.Context, arg RecordPickupParams) error {
	_, err := q.db.Exec(ctx, recordPickup,
		arg.Status,
		arg.Fault,
		arg.FeePolicy,
		arg.FeeAmount,
		arg.ID,
		arg.FromStatus,
	)
	return err
}

const rejectReturn = `-- name: RejectReturn :exec
UPDATE returns SET status = '거부', reject_reason = $2, updated_at = now()
WHERE id = $1
`

type RejectReturnParams struct {
	ID           string
	RejectReason string
}

func (q *Queries) RejectReturn(ctx context.Context, arg RejectReturnParams) error {
	_, err := q.db.Exec(ctx, rejectReturn, arg.ID, arg.RejectReason)
	return err
}

const reserveExchangePayment = `-- name: ReserveExchangePayment :one
INSERT INTO payments (order_id, return_id, kind, status, pg, payment_key, approved_amount)
VALUES ($1, $2, '교환차액', '대기', $3, $4, $5) RETURNING id
`

type ReserveExchangePaymentParams struct {
	OrderID        string
	ReturnID       *string
	Pg             string
	PaymentKey     string
	ApprovedAmount int32
}

func (q *Queries) ReserveExchangePayment(ctx context.Context, arg ReserveExchangePaymentParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveExchangePayment,
		arg.OrderID,
		arg.ReturnID,
		arg.Pg,
		arg.PaymentKey,
		arg.ApprovedAmount,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const returnByNo = `-- name: ReturnByNo :one
SELECT id, return_no, kind, status, reason, reject_reason,
       COALESCE(fault, '')::text AS fault, COALESCE(shipping_fee_policy, '')::text AS fee_policy,
       COALESCE(shipping_fee_amount, 0)::int AS fee_amount, COALESCE(new_variant_id::text, '')::text AS new_variant_id,
       COALESCE(price_difference, 0)::int AS price_difference, created_at
FROM returns WHERE return_no = $1
`

type ReturnByNoRow struct {
	ID              string
	ReturnNo        string
	Kind            string
	Status          string
	Reason          string
	RejectReason    string
	Fault           string
	FeePolicy       string
	FeeAmount       int32
	NewVariantID    string
	PriceDifference int32
	CreatedAt       time.Time
}

func (q *Queries) ReturnByNo(ctx context.Context, returnNo string) (ReturnByNoRow, error) {
	row := q.db.QueryRow(ctx, returnByNo, returnNo)
	var i ReturnByNoRow
	err := row.Scan(
		&i.ID,
		&i.ReturnNo,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.RejectReason,
		&i.Fault,
		&i.FeePolicy,
		&i.FeeAmount,
		&i.NewVariantID,
		&i.PriceDifference,
		&i.CreatedAt,
	)
	return i, err
}

const returnFeeSettings = `-- name: ReturnFeeSettings :many

SELECT key, value FROM settings WHERE key = ANY($1::text[])
`

type ReturnFeeSettingsRow struct {
	Key   string
	Value string
}

// 반품·교환 (returns.go, FR-617/FR-618). 수거를 거치지 않은 환불은 상태머신이 막는다.
func (q *Queries) ReturnFeeSettings(ctx context.Context, keys []string) ([]ReturnFeeSettingsRow, error) {
	rows, err := q.db.Query(ctx, returnFeeSettings, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnFeeSettingsRow{}
	for rows.Next() {
		var i ReturnFeeSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnItemQuantity = `-- name: ReturnItemQuantity :one
SELECT COALESCE(sum(quantity), 0)::int AS quantity FROM return_items WHERE return_id = $1
`

func (q *Queries) ReturnItemQuantity(ctx context.Context, returnID string) (int32, error) {
	row := q.db.QueryRow(ctx, returnItemQuantity, returnID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const returnItems = `-- name: ReturnItems :many
SELECT ri.order_item_id, oi.product_name, oi.option_label, ri.quantity, ri.is_open
FROM return_items ri JOIN order_items oi ON oi.id = ri.order_item_id
WHERE ri.return_id = $1 ORDER BY oi.created_at, oi.id
`

type ReturnItemsRow struct {
	OrderItemID string
	ProductName string
	OptionLabel string
	Quantity    int32
	IsOpen      bool
}

func (q *Queries) ReturnItems(ctx context.Context, returnID string) ([]ReturnItemsRow, error) {
	rows, err := q.db.Query(ctx, returnItems, returnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnItemsRow{}
	for rows.Next() {
		var i ReturnItemsRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.ProductName,
			&i.OptionLabel,
			&i.Quantity,
			&i.IsOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnItemsOf = `-- name: ReturnItemsOf :many
SELECT ri.return_id, ri.order_item_id, oi.product_name, oi.option_label, ri.quantity, ri.is_open
FROM return_items ri JOIN order_items oi ON oi.id = ri.order_item_id
WHERE ri.return_id = ANY($1::uuid[]) ORDER BY oi.created_at, oi.id
`

type ReturnItemsOfRow struct {
	ReturnID    string
	OrderItemID string
	ProductName string
	OptionLabel string
	Quantity    int32
	IsOpen      bool
}

func (q *Queries) ReturnItemsOf(ctx context.Context, returnIds []string) ([]ReturnItemsOfRow, error) {
	rows, err := q.db.Query(ctx, returnItemsOf, returnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnItemsOfRow{}
	for rows.Next() {
		var i ReturnItemsOfRow
		if err := rows.Scan(
			&i.ReturnID,
			&i.OrderItemID,
			&i.ProductName,
			&i.OptionLabel,
			&i.Quantity,
			&i.IsOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returns = `-- name: Returns :many
SELECT id, return_no, kind, status, reason, reject_reason,
       COALESCE(fault, '')::text AS fault, COALESCE(shipping_fee_policy, '')::text AS fee_policy,
       COALESCE(shipping_fee_amount, 0)::int AS fee_amount, COALESCE(new_variant_id::text, '')::text AS new_variant_id,
       COALESCE(price_difference, 0)::int AS price_difference, created_at
FROM returns WHERE order_id = $1 ORDER BY created_at DESC, id
`

type ReturnsRow struct {
	ID              string
	ReturnNo        string
	Kind            string
	Status          string
	Reason          string
	RejectReason    string
	Fault           string
	FeePolicy       string
	FeeAmount       int32
	NewVariantID    string
	PriceDifference int32
	CreatedAt       time.Time
}

func (q *Queries) Returns(ctx context.Context, orderID string) ([]ReturnsRow, error) {
	rows, err := q.db.Query(ctx, returns, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnsRow{}
	for rows.Next() {
		var i ReturnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReturnNo,
			&i.Kind,
			&i.Status,
			&i.Reason,
			&i.RejectReason,
			&i.Fault,
			&i.FeePolicy,
			&i.FeeAmount,
			&i.NewVariantID,
			&i.PriceDifference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReturnStatus = `-- name: SetReturnStatus :exec
UPDATE returns SET status = $2, updated_at = now() WHERE id = $1
`

type SetReturnStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetReturnStatus(ctx context.Context, arg SetReturnStatusParams) error {
	_, err := q.db.Exec(ctx, setReturnStatus, arg.ID, arg.Status)
	return err
}

const variantsForExchange = `-- name: VariantsForExchange :many
SELECT v.id, v.product_id, v.option_values, COALESCE(v.sku, '')::text AS sku,
       v.price_delta, v.stock, v.is_visible
FROM product_variants v
WHERE v.product_id = (SELECT oi.product_id FROM order_items oi WHERE oi.id = $1)
  AND v.id <> (SELECT oi.variant_id FROM order_items oi WHERE oi.id = $1)
  AND v.is_visible AND v.stock > 0
ORDER BY v.price_delta, v.id
`

type VariantsForExchangeRow struct {
	ID           string
	ProductID    string
	OptionValues []byte
	Sku          string
	PriceDelta   int32
	Stock        int32
	IsVisible    bool
}

func (q *Queries) VariantsForExchange(ctx context.Context, orderItemID string) ([]VariantsForExchangeRow, error) {
	rows, err := q.db.Query(ctx, variantsForExchange, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantsForExchangeRow{}
	for rows.Next() {
		var i VariantsForExchangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OptionValues,
			&i.Sku,
			&i.PriceDelta,
			&i.Stock,
			&i.IsVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
