// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package commerceq

import (
	"context"
)

const pickList = `-- name: PickList :many
SELECT oi.variant_id, oi.product_name, oi.option_label, oi.quantity
FROM order_items oi JOIN orders o ON o.id = oi.order_id
WHERE o.order_no = $1 ORDER BY oi.product_name
`

type PickListRow struct {
	VariantID   string
	ProductName string
	OptionLabel string
	Quantity    int32
}

func (q *Queries) PickList(ctx context.Context, orderNo string) ([]PickListRow, error) {
	rows, err := q.db.Query(ctx, pickList, orderNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PickListRow{}
	for rows.Next() {
		var i PickListRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductName,
			&i.OptionLabel,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiveStock = `-- name: ReceiveStock :one
UPDATE product_variants SET stock = stock + $1, updated_at = now()
WHERE id = $2 RETURNING stock
`

type ReceiveStockParams struct {
	Qty int32
	ID  string
}

func (q *Queries) ReceiveStock(ctx context.Context, arg ReceiveStockParams) (int32, error) {
	row := q.db.QueryRow(ctx, receiveStock, arg.Qty, arg.ID)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const scanVariant = `-- name: ScanVariant :one

SELECT v.id, v.product_id, p.name AS product_name, v.option_values, v.sku, v.stock
FROM product_variants v JOIN products p ON p.id = v.product_id
WHERE v.id = $1
`

type ScanVariantRow struct {
	ID           string
	ProductID    string
	ProductName  string
	OptionValues []byte
	Sku          *string
	Stock        int32
}

// 스캔·입고·실사·피킹 (scan.go, FR-620~623). 재고는 delta 로만 움직인다.
func (q *Queries) ScanVariant(ctx context.Context, id string) (ScanVariantRow, error) {
	row := q.db.QueryRow(ctx, scanVariant, id)
	var i ScanVariantRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.OptionValues,
		&i.Sku,
		&i.Stock,
	)
	return i, err
}

const stocktakeAdjust = `-- name: StocktakeAdjust :execrows
UPDATE product_variants SET stock = stock + $1, updated_at = now()
WHERE id = $2 AND stock = $3
`

type StocktakeAdjustParams struct {
	Delta  int32
	ID     string
	Ledger int32
}

func (q *Queries) StocktakeAdjust(ctx context.Context, arg StocktakeAdjustParams) (int64, error) {
	result, err := q.db.Exec(ctx, stocktakeAdjust, arg.Delta, arg.ID, arg.Ledger)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const variantStock = `-- name: VariantStock :one
SELECT stock FROM product_variants WHERE id = $1
`

func (q *Queries) VariantStock(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, variantStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}
