// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package commerceq

import (
	"context"
)

const addVariantStock = `-- name: AddVariantStock :exec
UPDATE product_variants SET stock = stock + $1, updated_at = now() WHERE id = $2
`

type AddVariantStockParams struct {
	Delta int32
	ID    string
}

func (q *Queries) AddVariantStock(ctx context.Context, arg AddVariantStockParams) error {
	_, err := q.db.Exec(ctx, addVariantStock, arg.Delta, arg.ID)
	return err
}

const advisoryXactLock = `-- name: AdvisoryXactLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AdvisoryXactLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, key)
	return err
}

const categories = `-- name: Categories :many
SELECT id, COALESCE(parent_id::text, '')::text AS parent_id, name, slug, sort_order
FROM categories ORDER BY sort_order, name, id
`

type CategoriesRow struct {
	ID        string
	ParentID  string
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) Categories(ctx context.Context) ([]CategoriesRow, error) {
	rows, err := q.db.Query(ctx, categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoriesRow{}
	for rows.Next() {
		var i CategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryBySlug = `-- name: CategoryBySlug :one
SELECT id, COALESCE(parent_id::text, '')::text AS parent_id, name, slug, sort_order
FROM categories WHERE slug = $1
`

type CategoryBySlugRow struct {
	ID        string
	ParentID  string
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) CategoryBySlug(ctx context.Context, slug string) (CategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, categoryBySlug, slug)
	var i CategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
	)
	return i, err
}

const categoryParents = `-- name: CategoryParents :many
SELECT id, COALESCE(parent_id::text, '')::text AS parent_id FROM categories
`

type CategoryParentsRow struct {
	ID       string
	ParentID string
}

func (q *Queries) CategoryParents(ctx context.Context) ([]CategoryParentsRow, error) {
	rows, err := q.db.Query(ctx, categoryParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryParentsRow{}
	for rows.Next() {
		var i CategoryParentsRow
		if err := rows.Scan(&i.ID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, name, slug, sort_order)
VALUES (NULLIF($1::text, '')::uuid, $2, $3, $4) RETURNING id
`

type CreateCategoryParams struct {
	ParentID  string
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (string, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (slug, name, description, base_price, is_visible)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateProductParams struct {
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (string, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.IsVisible,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProducts = `-- name: ListProducts :many

SELECT p.id, p.slug, p.name, p.description, p.base_price, p.is_visible,
       COALESCE(v.min_delta, 0)::int AS min_delta, COALESCE(v.in_stock, false)::boolean AS in_stock
FROM (
    SELECT p.id, p.slug, p.name, p.description, p.base_price, p.is_visible, p.created_at
    FROM products p
    WHERE ($1::boolean IS NOT TRUE OR p.is_visible)
      AND ($2::uuid IS NULL OR EXISTS (
            SELECT 1 FROM product_categories pc
            WHERE pc.product_id = p.id AND pc.category_id = $2))
    ORDER BY
        CASE WHEN $3::text = 'price'      THEN p.base_price END,
        CASE WHEN $3::text = 'price_desc' THEN p.base_price END DESC,
        CASE WHEN $3::text = 'name'       THEN p.name END,
        CASE WHEN $3::text IN ('', 'new') THEN p.created_at END DESC,
        p.id
    LIMIT $5::int OFFSET $4::int
) p
LEFT JOIN LATERAL (
    SELECT min(price_delta) AS min_delta, bool_or(stock > 0) AS in_stock
    FROM product_variants
    WHERE product_id = p.id AND is_visible
) v ON true
ORDER BY
    CASE WHEN $3::text = 'price'      THEN p.base_price END,
    CASE WHEN $3::text = 'price_desc' THEN p.base_price END DESC,
    CASE WHEN $3::text = 'name'       THEN p.name END,
    CASE WHEN $3::text IN ('', 'new') THEN p.created_at END DESC,
    p.id
`

type ListProductsParams struct {
	VisibleOnly bool
	CategoryID  *string
	Sort        string
	Offset      int32
	Limit       int32
}

type ListProductsRow struct {
	ID          string
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
	MinDelta    int32
	InStock     bool
}

// 상품·조합·카테고리·검색 (store.go). 정렬 키는 CASE 로 한 질의에 담는다 (D22 6절).
// **쪽을 먼저 고르고, 조합 요약은 그 행에만 붙인다** (ListProducts·SearchProducts).
// 한 층으로 쓰면 정렬이 인덱스를 못 타는 순간 걸러진 상품 **전부**의 조합을 집계하고
// 나서 정렬한다. 바깥 ORDER BY 는 안쪽과 같다 — 조인이 순서를 지켜 준다는 보장은 없다.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.VisibleOnly,
		arg.CategoryID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.IsVisible,
			&i.MinDelta,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVariantStock = `-- name: LockVariantStock :one
SELECT stock FROM product_variants WHERE id = $1 FOR NO KEY UPDATE
`

// FOR NO KEY UPDATE: 뒤따르는 UPDATE 는 키 컬럼을 바꾸지 않는다. FOR UPDATE 는
// 외래키 검사(FOR KEY SHARE)까지 막아, 재고를 잠근 동안 그 조합을 장바구니에 담는
// INSERT 가 줄을 선다.
func (q *Queries) LockVariantStock(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, lockVariantStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const productBySlug = `-- name: ProductBySlug :one
SELECT id, slug, name, description, base_price, is_visible
FROM products WHERE slug = $1 AND ($2::boolean IS NOT TRUE OR is_visible)
`

type ProductBySlugParams struct {
	Slug        string
	VisibleOnly bool
}

type ProductBySlugRow struct {
	ID          string
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
}

func (q *Queries) ProductBySlug(ctx context.Context, arg ProductBySlugParams) (ProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, productBySlug, arg.Slug, arg.VisibleOnly)
	var i ProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.IsVisible,
	)
	return i, err
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id, p.slug, p.name, p.description, p.base_price, p.is_visible,
       COALESCE(v.min_delta, 0)::int AS min_delta, COALESCE(v.in_stock, false)::boolean AS in_stock
FROM (
    SELECT p.id, p.slug, p.name, p.description, p.base_price, p.is_visible,
           ts_rank(p.search_tsv, to_tsquery('simple', $1)) AS rank
    FROM products p
    WHERE p.is_visible AND p.search_tsv @@ to_tsquery('simple', $1)
    ORDER BY rank DESC, p.id
    LIMIT $3::int OFFSET $2::int
) p
LEFT JOIN LATERAL (
    SELECT min(price_delta) AS min_delta, bool_or(stock > 0) AS in_stock
    FROM product_variants WHERE product_id = p.id AND is_visible
) v ON true
ORDER BY p.rank DESC, p.id
`

type SearchProductsParams struct {
	Query  string
	Offset int32
	Limit  int32
}

type SearchProductsRow struct {
	ID          string
	Slug        string
	Name        string
	Description string
	BasePrice   int32
	IsVisible   bool
	MinDelta    int32
	InStock     bool
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.IsVisible,
			&i.MinDelta,
			&i.InStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryParent = `-- name: SetCategoryParent :exec
UPDATE categories SET parent_id = $1, updated_at = now() WHERE id = $2
`

type SetCategoryParentParams struct {
	ParentID *string
	ID       string
}

func (q *Queries) SetCategoryParent(ctx context.Context, arg SetCategoryParentParams) error {
	_, err := q.db.Exec(ctx, setCategoryParent, arg.ParentID, arg.ID)
	return err
}

const variantForPurchase = `-- name: VariantForPurchase :one
SELECT v.id, v.product_id, v.option_values, COALESCE(v.sku, '')::text AS sku, v.price_delta,
       v.stock, v.is_visible, p.is_visible AS product_visible, p.base_price
FROM product_variants v JOIN products p ON p.id = v.product_id
WHERE v.id = $1
`

type VariantForPurchaseRow struct {
	ID             string
	ProductID      string
	OptionValues   []byte
	Sku            string
	PriceDelta     int32
	Stock          int32
	IsVisible      bool
	ProductVisible bool
	BasePrice      int32
}

func (q *Queries) VariantForPurchase(ctx context.Context, id string) (VariantForPurchaseRow, error) {
	row := q.db.QueryRow(ctx, variantForPurchase, id)
	var i VariantForPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.OptionValues,
		&i.Sku,
		&i.PriceDelta,
		&i.Stock,
		&i.IsVisible,
		&i.ProductVisible,
		&i.BasePrice,
	)
	return i, err
}

const variants = `-- name: Variants :many
SELECT id, product_id, option_values, COALESCE(sku, '')::text AS sku, price_delta, stock, is_visible
FROM product_variants
WHERE product_id = $1 AND ($2::boolean IS NOT TRUE OR (is_visible AND stock > 0))
ORDER BY price_delta, id
`

type VariantsParams struct {
	ProductID    string
	SellableOnly bool
}

type VariantsRow struct {
	ID           string
	ProductID    string
	OptionValues []byte
	Sku          string
	PriceDelta   int32
	Stock        int32
	IsVisible    bool
}

func (q *Queries) Variants(ctx context.Context, arg VariantsParams) ([]VariantsRow, error) {
	rows, err := q.db.Query(ctx, variants, arg.ProductID, arg.SellableOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantsRow{}
	for rows.Next() {
		var i VariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OptionValues,
			&i.Sku,
			&i.PriceDelta,
			&i.Stock,
			&i.IsVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
