// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package commerceq

import (
	"context"
	"time"
)

const addTerms = `-- name: AddTerms :one
INSERT INTO terms (kind, version, body, effective_at, is_required)
VALUES ($1, $2, $3, GREATEST($4::timestamptz, now()), $5) RETURNING id
`

type AddTermsParams struct {
	Kind        string
	Version     string
	Body        string
	EffectiveAt time.Time
	IsRequired  bool
}

func (q *Queries) AddTerms(ctx context.Context, arg AddTermsParams) (string, error) {
	row := q.db.QueryRow(ctx, addTerms,
		arg.Kind,
		arg.Version,
		arg.Body,
		arg.EffectiveAt,
		arg.IsRequired,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listTerms = `-- name: ListTerms :many

SELECT t.id, t.kind, t.version, t.body, t.effective_at, t.is_required, t.created_at,
       EXISTS (SELECT 1 FROM order_agreements a WHERE a.terms_id = t.id)::boolean AS in_use
FROM terms t ORDER BY t.kind, t.effective_at DESC
`

type ListTermsRow struct {
	ID          string
	Kind        string
	Version     string
	Body        string
	EffectiveAt time.Time
	IsRequired  bool
	CreatedAt   time.Time
	InUse       bool
}

// 약관 (terms.go, FR-619). UPDATE 가 없다 — 개정은 새 행이다.
func (q *Queries) ListTerms(ctx context.Context) ([]ListTermsRow, error) {
	rows, err := q.db.Query(ctx, listTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTermsRow{}
	for rows.Next() {
		var i ListTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Body,
			&i.EffectiveAt,
			&i.IsRequired,
			&i.CreatedAt,
			&i.InUse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requiredTerms = `-- name: RequiredTerms :many
SELECT DISTINCT ON (kind) id, kind, version, body, effective_at, is_required, created_at
FROM terms
WHERE is_required AND effective_at <= $1
ORDER BY kind, effective_at DESC
`

func (q *Queries) RequiredTerms(ctx context.Context, now time.Time) ([]Term, error) {
	rows, err := q.db.Query(ctx, requiredTerms, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Body,
			&i.EffectiveAt,
			&i.IsRequired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const termsByID = `-- name: TermsByID :one
SELECT id, kind, version, body, effective_at, is_required, created_at
FROM terms WHERE id = $1
`

func (q *Queries) TermsByID(ctx context.Context, id string) (Term, error) {
	row := q.db.QueryRow(ctx, termsByID, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Body,
		&i.EffectiveAt,
		&i.IsRequired,
		&i.CreatedAt,
	)
	return i, err
}
