// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package commerceq

import (
	"context"
	"time"
)

const approvePendingPayment = `-- name: ApprovePendingPayment :execrows
UPDATE payments SET status = '승인', approved_at = now(), raw_response = $1,
       updated_at = now()
WHERE id = $2 AND status = '대기'
`

type ApprovePendingPaymentParams struct {
	RawResponse []byte
	ID          string
}

func (q *Queries) ApprovePendingPayment(ctx context.Context, arg ApprovePendingPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePendingPayment, arg.RawResponse, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishWebhook = `-- name: FinishWebhook :exec
UPDATE webhook_events SET status = $1, error = NULLIF($2::text, ''), updated_at = now()
WHERE id = $3
`

type FinishWebhookParams struct {
	Status string
	Error  string
	ID     string
}

func (q *Queries) FinishWebhook(ctx context.Context, arg FinishWebhookParams) error {
	_, err := q.db.Exec(ctx, finishWebhook, arg.Status, arg.Error, arg.ID)
	return err
}

const livePayment = `-- name: LivePayment :one
SELECT id, payment_key, status, COALESCE(secret, '')::text AS secret FROM payments
WHERE order_id = $1 AND kind = '주문결제' AND status <> '실패'
`

type LivePaymentRow struct {
	ID         string
	PaymentKey string
	Status     string
	Secret     string
}

func (q *Queries) LivePayment(ctx context.Context, orderID string) (LivePaymentRow, error) {
	row := q.db.QueryRow(ctx, livePayment, orderID)
	var i LivePaymentRow
	err := row.Scan(
		&i.ID,
		&i.PaymentKey,
		&i.Status,
		&i.Secret,
	)
	return i, err
}

const orderForWebhook = `-- name: OrderForWebhook :one
SELECT id, status, total_amount FROM orders WHERE order_no = $1
`

type OrderForWebhookRow struct {
	ID          string
	Status      string
	TotalAmount int32
}

func (q *Queries) OrderForWebhook(ctx context.Context, orderNo string) (OrderForWebhookRow, error) {
	row := q.db.QueryRow(ctx, orderForWebhook, orderNo)
	var i OrderForWebhookRow
	err := row.Scan(&i.ID, &i.Status, &i.TotalAmount)
	return i, err
}

const paymentsToReconcile = `-- name: PaymentsToReconcile :many
SELECT p.id, p.payment_key, o.order_no, p.pg, p.kind, p.status,
       p.approved_amount, p.refunded_amount, p.created_at
FROM payments p JOIN orders o ON o.id = p.order_id
WHERE p.created_at >= $1 AND p.created_at < $2
ORDER BY (p.status = '대기') DESC, p.created_at DESC
LIMIT 500
`

type PaymentsToReconcileParams struct {
	Since time.Time
	Until time.Time
}

type PaymentsToReconcileRow struct {
	ID             string
	PaymentKey     string
	OrderNo        string
	Pg             string
	Kind           string
	Status         string
	ApprovedAmount int32
	RefundedAmount int32
	CreatedAt      time.Time
}

func (q *Queries) PaymentsToReconcile(ctx context.Context, arg PaymentsToReconcileParams) ([]PaymentsToReconcileRow, error) {
	rows, err := q.db.Query(ctx, paymentsToReconcile, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsToReconcileRow{}
	for rows.Next() {
		var i PaymentsToReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentKey,
			&i.OrderNo,
			&i.Pg,
			&i.Kind,
			&i.Status,
			&i.ApprovedAmount,
			&i.RefundedAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhook = `-- name: RecordWebhook :one

INSERT INTO webhook_events (pg, event_id, order_id, status, payload)
VALUES ($1, $2, (SELECT id FROM orders WHERE order_no = $3), '수신', $4)
RETURNING id
`

type RecordWebhookParams struct {
	Pg      string
	EventID string
	OrderNo string
	Payload []byte
}

// 웹훅·대사 (webhook.go, FR-610, A-508/A-603). 멱등은 유니크 인덱스가 판단한다.
func (q *Queries) RecordWebhook(ctx context.Context, arg RecordWebhookParams) (string, error) {
	row := q.db.QueryRow(ctx, recordWebhook,
		arg.Pg,
		arg.EventID,
		arg.OrderNo,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const webhookHistory = `-- name: WebhookHistory :many
SELECT w.id, w.pg, w.event_id, COALESCE(o.order_no, '')::text AS order_no, w.status,
       w.payload::text AS payload, COALESCE(w.error, '')::text AS error, w.created_at
FROM webhook_events w LEFT JOIN orders o ON o.id = w.order_id
ORDER BY (w.status = '수신') DESC, w.created_at DESC, w.id
LIMIT $1::int
`

type WebhookHistoryRow struct {
	ID        string
	Pg        string
	EventID   string
	OrderNo   string
	Status    string
	Payload   string
	Error     string
	CreatedAt time.Time
}

func (q *Queries) WebhookHistory(ctx context.Context, limit int32) ([]WebhookHistoryRow, error) {
	rows, err := q.db.Query(ctx, webhookHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookHistoryRow{}
	for rows.Next() {
		var i WebhookHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Pg,
			&i.EventID,
			&i.OrderNo,
			&i.Status,
			&i.Payload,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
