// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: install.sql

package installq

import (
	"context"
)

const createFirstAdmin = `-- name: CreateFirstAdmin :execrows
WITH created AS (
    INSERT INTO users (email, password_hash, display_name)
    VALUES ($1, $2, $3)
    ON CONFLICT (email) DO NOTHING
    RETURNING id
)
INSERT INTO user_roles (user_id, role_id)
SELECT created.id, r.id FROM created, roles r WHERE r.key = 'admin'
`

type CreateFirstAdminParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) CreateFirstAdmin(ctx context.Context, arg CreateFirstAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFirstAdmin, arg.Email, arg.PasswordHash, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
