// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package contentq

import (
	"context"
	"time"
)

const attachmentByID = `-- name: AttachmentByID :one
SELECT id, post_id, stored_path, original_name, mime_type, byte_size, created_at
FROM attachments WHERE id = $1
`

func (q *Queries) AttachmentByID(ctx context.Context, id string) (Attachment, error) {
	row := q.db.QueryRow(ctx, attachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.StoredPath,
		&i.OriginalName,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const attachmentPaths = `-- name: AttachmentPaths :many
SELECT stored_path FROM attachments WHERE post_id = $1
`

func (q *Queries) AttachmentPaths(ctx context.Context, postID string) ([]string, error) {
	rows, err := q.db.Query(ctx, attachmentPaths, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var stored_path string
		if err := rows.Scan(&stored_path); err != nil {
			return nil, err
		}
		items = append(items, stored_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachments = `-- name: Attachments :many
SELECT id, post_id, stored_path, original_name, mime_type, byte_size, created_at
FROM attachments WHERE post_id = $1 ORDER BY created_at, id
`

func (q *Queries) Attachments(ctx context.Context, postID string) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, attachments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.StoredPath,
			&i.OriginalName,
			&i.MimeType,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardAttachments = `-- name: BoardAttachments :many
SELECT a.id, a.post_id, a.stored_path, a.original_name, a.mime_type, a.byte_size, a.created_at
FROM attachments a
JOIN posts p ON p.id = a.post_id
WHERE p.board_id = $1
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2
`

type BoardAttachmentsParams struct {
	BoardID string
	Limit   int32
}

func (q *Queries) BoardAttachments(ctx context.Context, arg BoardAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, boardAttachments, arg.BoardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.StoredPath,
			&i.OriginalName,
			&i.MimeType,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttachments = `-- name: CountAttachments :one
SELECT count(*) FROM attachments WHERE post_id = $1
`

func (q *Queries) CountAttachments(ctx context.Context, postID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (post_id, stored_path, original_name, mime_type, byte_size)
VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at
`

type CreateAttachmentParams struct {
	PostID       string
	StoredPath   string
	OriginalName string
	MimeType     string
	ByteSize     int64
}

type CreateAttachmentRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.PostID,
		arg.StoredPath,
		arg.OriginalName,
		arg.MimeType,
		arg.ByteSize,
	)
	var i CreateAttachmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
