// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package contentq

import (
	"context"
)

const boardByID = `-- name: BoardByID :one
SELECT id, slug, name, skin, allow_attachments, allow_comments, allow_secret, per_page, created_at, updated_at
FROM boards WHERE id = $1
`

func (q *Queries) BoardByID(ctx context.Context, id string) (Board, error) {
	row := q.db.QueryRow(ctx, boardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Skin,
		&i.AllowAttachments,
		&i.AllowComments,
		&i.AllowSecret,
		&i.PerPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const boardByPost = `-- name: BoardByPost :one
SELECT b.id, b.slug, b.name, b.skin, b.allow_attachments, b.allow_comments, b.allow_secret, b.per_page, b.created_at, b.updated_at
FROM boards b JOIN posts p ON p.board_id = b.id
WHERE p.id = $1
`

func (q *Queries) BoardByPost(ctx context.Context, id string) (Board, error) {
	row := q.db.QueryRow(ctx, boardByPost, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Skin,
		&i.AllowAttachments,
		&i.AllowComments,
		&i.AllowSecret,
		&i.PerPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const boardBySlug = `-- name: BoardBySlug :one
SELECT id, slug, name, skin, allow_attachments, allow_comments, allow_secret, per_page, created_at, updated_at
FROM boards WHERE slug = $1
`

func (q *Queries) BoardBySlug(ctx context.Context, slug string) (Board, error) {
	row := q.db.QueryRow(ctx, boardBySlug, slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Skin,
		&i.AllowAttachments,
		&i.AllowComments,
		&i.AllowSecret,
		&i.PerPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const boardFields = `-- name: BoardFields :many
SELECT key, label, field_type, is_required, show_in_list, options, sort_order
FROM board_fields WHERE board_id = $1 ORDER BY sort_order, key
`

type BoardFieldsRow struct {
	Key        string
	Label      string
	FieldType  string
	IsRequired bool
	ShowInList bool
	Options    []byte
	SortOrder  int32
}

func (q *Queries) BoardFields(ctx context.Context, boardID string) ([]BoardFieldsRow, error) {
	rows, err := q.db.Query(ctx, boardFields, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardFieldsRow{}
	for rows.Next() {
		var i BoardFieldsRow
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.FieldType,
			&i.IsRequired,
			&i.ShowInList,
			&i.Options,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boards = `-- name: Boards :many
SELECT id, slug, name, skin, allow_attachments, allow_comments, allow_secret, per_page, created_at, updated_at
FROM boards ORDER BY name, id
`

func (q *Queries) Boards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, boards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Skin,
			&i.AllowAttachments,
			&i.AllowComments,
			&i.AllowSecret,
			&i.PerPage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBoardPosts = `-- name: CountBoardPosts :one
SELECT count(*) FROM posts WHERE board_id = $1
`

func (q *Queries) CountBoardPosts(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBoardPosts, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (slug, name, skin, allow_attachments, allow_comments, allow_secret, per_page)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type CreateBoardParams struct {
	Slug             string
	Name             string
	Skin             string
	AllowAttachments bool
	AllowComments    bool
	AllowSecret      bool
	PerPage          int32
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (string, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.Slug,
		arg.Name,
		arg.Skin,
		arg.AllowAttachments,
		arg.AllowComments,
		arg.AllowSecret,
		arg.PerPage,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
DELETE FROM boards WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardField = `-- name: DeleteBoardField :execrows
DELETE FROM board_fields WHERE board_id = $1 AND key = $2
`

type DeleteBoardFieldParams struct {
	BoardID string
	Key     string
}

func (q *Queries) DeleteBoardField(ctx context.Context, arg DeleteBoardFieldParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardField, arg.BoardID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const grantBoardPreset = `-- name: GrantBoardPreset :execrows
INSERT INTO role_permissions (role_id, permission_id, board_id)
SELECT r.id, p.id, $1::uuid FROM roles r, permissions p
WHERE r.key = $2 AND p.key = $3 AND p.is_scoped
`

type GrantBoardPresetParams struct {
	BoardID    string
	Role       string
	Permission string
}

func (q *Queries) GrantBoardPreset(ctx context.Context, arg GrantBoardPresetParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantBoardPreset, arg.BoardID, arg.Role, arg.Permission)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveBoardField = `-- name: SaveBoardField :exec
INSERT INTO board_fields (board_id, key, label, field_type, is_required, show_in_list, options, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (board_id, key) DO UPDATE SET
    label = EXCLUDED.label, field_type = EXCLUDED.field_type,
    is_required = EXCLUDED.is_required, show_in_list = EXCLUDED.show_in_list,
    options = EXCLUDED.options, sort_order = EXCLUDED.sort_order, updated_at = now()
`

type SaveBoardFieldParams struct {
	BoardID    string
	Key        string
	Label      string
	FieldType  string
	IsRequired bool
	ShowInList bool
	Options    []byte
	SortOrder  int32
}

func (q *Queries) SaveBoardField(ctx context.Context, arg SaveBoardFieldParams) error {
	_, err := q.db.Exec(ctx, saveBoardField,
		arg.BoardID,
		arg.Key,
		arg.Label,
		arg.FieldType,
		arg.IsRequired,
		arg.ShowInList,
		arg.Options,
		arg.SortOrder,
	)
	return err
}

const updateBoard = `-- name: UpdateBoard :execrows
UPDATE boards SET name = $2, skin = $3, allow_attachments = $4,
       allow_comments = $5, allow_secret = $6, per_page = $7, updated_at = now()
WHERE id = $1
`

type UpdateBoardParams struct {
	ID               string
	Name             string
	Skin             string
	AllowAttachments bool
	AllowComments    bool
	AllowSecret      bool
	PerPage          int32
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.Skin,
		arg.AllowAttachments,
		arg.AllowComments,
		arg.AllowSecret,
		arg.PerPage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
