// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customfield.sql

package contentq

import (
	"context"
)

const deleteUserField = `-- name: DeleteUserField :execrows
DELETE FROM user_fields WHERE key = $1
`

func (q *Queries) DeleteUserField(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserField, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveUserField = `-- name: SaveUserField :exec
INSERT INTO user_fields (key, label, field_type, is_required, show_in_list, options, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (key) DO UPDATE SET
    label = EXCLUDED.label, field_type = EXCLUDED.field_type,
    is_required = EXCLUDED.is_required, show_in_list = EXCLUDED.show_in_list,
    options = EXCLUDED.options, sort_order = EXCLUDED.sort_order, updated_at = now()
`

type SaveUserFieldParams struct {
	Key        string
	Label      string
	FieldType  string
	IsRequired bool
	ShowInList bool
	Options    []byte
	SortOrder  int32
}

func (q *Queries) SaveUserField(ctx context.Context, arg SaveUserFieldParams) error {
	_, err := q.db.Exec(ctx, saveUserField,
		arg.Key,
		arg.Label,
		arg.FieldType,
		arg.IsRequired,
		arg.ShowInList,
		arg.Options,
		arg.SortOrder,
	)
	return err
}

const userFields = `-- name: UserFields :many
SELECT key, label, field_type, is_required, show_in_list, options, sort_order
FROM user_fields ORDER BY sort_order, key
`

type UserFieldsRow struct {
	Key        string
	Label      string
	FieldType  string
	IsRequired bool
	ShowInList bool
	Options    []byte
	SortOrder  int32
}

func (q *Queries) UserFields(ctx context.Context) ([]UserFieldsRow, error) {
	rows, err := q.db.Query(ctx, userFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFieldsRow{}
	for rows.Next() {
		var i UserFieldsRow
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.FieldType,
			&i.IsRequired,
			&i.ShowInList,
			&i.Options,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
