// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oplog.sql

package contentq

import (
	"context"
	"net/netip"
	"time"
)

const countOpLog = `-- name: CountOpLog :one
SELECT count(*) FROM operation_logs
`

func (q *Queries) CountOpLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recentOpLog = `-- name: RecentOpLog :many
SELECT id, actor_email, action, target_type, coalesce(target_id, '') AS target_id,
       summary, coalesce(host(ip), '')::text AS ip, created_at
FROM operation_logs ORDER BY created_at DESC, id DESC LIMIT $2::int OFFSET $1::int
`

type RecentOpLogParams struct {
	Offset int32
	Limit  int32
}

type RecentOpLogRow struct {
	ID         string
	ActorEmail string
	Action     string
	TargetType string
	TargetID   string
	Summary    string
	Ip         string
	CreatedAt  time.Time
}

func (q *Queries) RecentOpLog(ctx context.Context, arg RecentOpLogParams) ([]RecentOpLogRow, error) {
	rows, err := q.db.Query(ctx, recentOpLog, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentOpLogRow{}
	for rows.Next() {
		var i RecentOpLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Summary,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOpLog = `-- name: RecordOpLog :exec
INSERT INTO operation_logs
    (actor_user_id, actor_email, action, target_type, target_id, summary, ip)
VALUES ($5, $1, $2, $3, $6, $4, $7::inet)
`

type RecordOpLogParams struct {
	ActorEmail  string
	Action      string
	TargetType  string
	Summary     string
	ActorUserID *string
	TargetID    *string
	Ip          *netip.Addr
}

func (q *Queries) RecordOpLog(ctx context.Context, arg RecordOpLogParams) error {
	_, err := q.db.Exec(ctx, recordOpLog,
		arg.ActorEmail,
		arg.Action,
		arg.TargetType,
		arg.Summary,
		arg.ActorUserID,
		arg.TargetID,
		arg.Ip,
	)
	return err
}
