// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package contentq

import (
	"context"
	"time"
)

const bumpViewCount = `-- name: BumpViewCount :exec
UPDATE posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) BumpViewCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpViewCount, id)
	return err
}

const commentByID = `-- name: CommentByID :one
SELECT id, post_id, coalesce(parent_id::text, '')::text AS parent_id, coalesce(author_id::text, '')::text AS author_id,
       body, coalesce(deleted_at, 'epoch'::timestamptz)::timestamptz AS deleted_at, created_at
FROM comments WHERE id = $1
`

type CommentByIDRow struct {
	ID        string
	PostID    string
	ParentID  string
	AuthorID  string
	Body      string
	DeletedAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CommentByID(ctx context.Context, id string) (CommentByIDRow, error) {
	row := q.db.QueryRow(ctx, commentByID, id)
	var i CommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const comments = `-- name: Comments :many
SELECT c.id, c.post_id, coalesce(c.parent_id::text, '')::text AS parent_id,
       coalesce(c.author_id::text, '')::text AS author_id, coalesce(u.display_name, '')::text AS author_name,
       c.body, coalesce(c.deleted_at, 'epoch'::timestamptz)::timestamptz AS deleted_at, c.created_at
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.post_id = $1
ORDER BY coalesce(c.parent_id, c.id), c.created_at, c.id
`

type CommentsRow struct {
	ID         string
	PostID     string
	ParentID   string
	AuthorID   string
	AuthorName string
	Body       string
	DeletedAt  time.Time
	CreatedAt  time.Time
}

func (q *Queries) Comments(ctx context.Context, postID string) ([]CommentsRow, error) {
	rows, err := q.db.Query(ctx, comments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentsRow{}
	for rows.Next() {
		var i CommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPosts = `-- name: CountPosts :one
SELECT count(*) FROM posts p
WHERE p.board_id = $1 AND p.status = 'published'
`

func (q *Queries) CountPosts(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsSearch = `-- name: CountPostsSearch :one
SELECT count(*) FROM posts p
WHERE p.board_id = $1 AND p.status = 'published'
  AND p.search_vector @@ to_tsquery('simple', $2)
`

type CountPostsSearchParams struct {
	BoardID string
	Search  string
}

func (q *Queries) CountPostsSearch(ctx context.Context, arg CountPostsSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsSearch, arg.BoardID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchPosts = `-- name: CountSearchPosts :one
SELECT count(*) FROM posts p
WHERE p.board_id = ANY($1::uuid[]) AND p.status = 'published'
  AND (NOT p.is_secret OR p.board_id = ANY($2::uuid[]) OR p.author_id = $3)
  AND p.search_vector @@ to_tsquery('simple', $4)
`

type CountSearchPostsParams struct {
	Readable []string
	SecretIn []string
	ViewerID *string
	Search   string
}

func (q *Queries) CountSearchPosts(ctx context.Context, arg CountSearchPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchPosts,
		arg.Readable,
		arg.SecretIn,
		arg.ViewerID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, parent_id, author_id, body)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateCommentParams struct {
	PostID   string
	ParentID *string
	AuthorID *string
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (string, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (board_id, author_id, title, body, custom_fields, is_secret)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreatePostParams struct {
	BoardID      string
	AuthorID     *string
	Title        string
	Body         string
	CustomFields []byte
	IsSecret     bool
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (string, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.BoardID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.CustomFields,
		arg.IsSecret,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moderateComments = `-- name: ModerateComments :many
SELECT c.id, c.post_id, coalesce(c.parent_id::text, '')::text AS parent_id,
       coalesce(c.author_id::text, '')::text AS author_id, coalesce(u.display_name, '')::text AS author_name,
       c.body, coalesce(c.deleted_at, 'epoch'::timestamptz)::timestamptz AS deleted_at, c.created_at
FROM comments c
JOIN posts p ON p.id = c.post_id
LEFT JOIN users u ON u.id = c.author_id
WHERE p.board_id = $1
ORDER BY c.created_at DESC, c.id DESC
LIMIT $2
`

type ModerateCommentsParams struct {
	BoardID string
	Limit   int32
}

type ModerateCommentsRow struct {
	ID         string
	PostID     string
	ParentID   string
	AuthorID   string
	AuthorName string
	Body       string
	DeletedAt  time.Time
	CreatedAt  time.Time
}

func (q *Queries) ModerateComments(ctx context.Context, arg ModerateCommentsParams) ([]ModerateCommentsRow, error) {
	rows, err := q.db.Query(ctx, moderateComments, arg.BoardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerateCommentsRow{}
	for rows.Next() {
		var i ModerateCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPostFlags = `-- name: SetPostFlags :execrows
UPDATE posts SET is_pinned = $2, status = $3, updated_at = now() WHERE id = $1
`

type SetPostFlagsParams struct {
	ID       string
	IsPinned bool
	Status   string
}

func (q *Queries) SetPostFlags(ctx context.Context, arg SetPostFlagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPostFlags, arg.ID, arg.IsPinned, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sitemapPosts = `-- name: SitemapPosts :many
SELECT id, board_id, updated_at FROM (
    SELECT id, board_id, updated_at,
           row_number() OVER (PARTITION BY board_id ORDER BY created_at DESC, id DESC) AS rn
    FROM posts
    WHERE board_id = ANY($1::uuid[]) AND status = 'published' AND NOT is_secret
) t
WHERE rn <= $2::int
ORDER BY board_id, rn
`

type SitemapPostsParams struct {
	BoardIds []string
	PerBoard int32
}

type SitemapPostsRow struct {
	ID        string
	BoardID   string
	UpdatedAt time.Time
}

func (q *Queries) SitemapPosts(ctx context.Context, arg SitemapPostsParams) ([]SitemapPostsRow, error) {
	rows, err := q.db.Query(ctx, sitemapPosts, arg.BoardIds, arg.PerBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitemapPostsRow{}
	for rows.Next() {
		var i SitemapPostsRow
		if err := rows.Scan(&i.ID, &i.BoardID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneComment = `-- name: TombstoneComment :execrows
UPDATE comments SET body = '', deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TombstoneComment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComment = `-- name: UpdateComment :execrows
UPDATE comments SET body = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCommentParams struct {
	ID   string
	Body string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComment, arg.ID, arg.Body)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE posts SET title = $2, body = $3, custom_fields = $4, is_secret = $5,
       updated_at = now()
WHERE id = $1
`

type UpdatePostParams struct {
	ID           string
	Title        string
	Body         string
	CustomFields []byte
	IsSecret     bool
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.CustomFields,
		arg.IsSecret,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
