// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package contentq

import (
	"context"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menus (title, url, parent_id, sort_order)
VALUES ($1, $2, nullif($4::text, '')::uuid, $3) RETURNING id
`

type CreateMenuItemParams struct {
	Title     string
	Url       string
	SortOrder int32
	ParentID  string
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (string, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.Title,
		arg.Url,
		arg.SortOrder,
		arg.ParentID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (slug, title, body, template)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreatePageParams struct {
	Slug     string
	Title    string
	Body     string
	Template string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (string, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.Template,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :execrows
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMenuItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const legacySecretSettings = `-- name: LegacySecretSettings :many
SELECT key, value FROM settings
WHERE (key IN ('pg.secret_key', 'mail.smtp_password') OR key LIKE 'social.%.client_secret')
  AND value <> '' AND value NOT LIKE 'enc:v1:%'
`

type LegacySecretSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) LegacySecretSettings(ctx context.Context) ([]LegacySecretSettingsRow, error) {
	rows, err := q.db.Query(ctx, legacySecretSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegacySecretSettingsRow{}
	for rows.Next() {
		var i LegacySecretSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuItems = `-- name: MenuItems :many
SELECT id, coalesce(parent_id::text, '')::text AS parent_id, title, url, sort_order
FROM menus
ORDER BY parent_id NULLS FIRST, sort_order, id
`

type MenuItemsRow struct {
	ID        string
	ParentID  string
	Title     string
	Url       string
	SortOrder int32
}

func (q *Queries) MenuItems(ctx context.Context) ([]MenuItemsRow, error) {
	rows, err := q.db.Query(ctx, menuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItemsRow{}
	for rows.Next() {
		var i MenuItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Url,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageByID = `-- name: PageByID :one
SELECT id, slug, title, body, status, template, created_at, updated_at
FROM pages WHERE id = $1
`

func (q *Queries) PageByID(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRow(ctx, pageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Template,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pageBySlug = `-- name: PageBySlug :one
SELECT id, slug, title, body, status, template, created_at, updated_at
FROM pages WHERE slug = $1
`

func (q *Queries) PageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, pageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Template,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pageStatus = `-- name: PageStatus :one
SELECT status FROM pages WHERE id = $1
`

func (q *Queries) PageStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, pageStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const pages = `-- name: Pages :many
SELECT id, slug, title, body, status, template, created_at, updated_at
FROM pages ORDER BY updated_at DESC, id
`

func (q *Queries) Pages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, pages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Template,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishedPageBySlug = `-- name: PublishedPageBySlug :one
SELECT id, slug, title, body, status, template, created_at, updated_at
FROM pages WHERE slug = $1 AND status = 'published'
`

func (q *Queries) PublishedPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, publishedPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Template,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishedPages = `-- name: PublishedPages :many
SELECT id, slug, title, body, status, template, created_at, updated_at
FROM pages WHERE status = 'published' ORDER BY slug
`

func (q *Queries) PublishedPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, publishedPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Template,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type PutSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value)
	return err
}

const setPageStatus = `-- name: SetPageStatus :execrows
UPDATE pages SET status = $2, updated_at = now()
WHERE id = $1 AND status = $3
`

type SetPageStatusParams struct {
	ID   string
	To   string
	From string
}

func (q *Queries) SetPageStatus(ctx context.Context, arg SetPageStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPageStatus, arg.ID, arg.To, arg.From)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settings = `-- name: Settings :many
SELECT key, value FROM settings WHERE key = ANY($1::text[])
`

type SettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) Settings(ctx context.Context, keys []string) ([]SettingsRow, error) {
	rows, err := q.db.Query(ctx, settings, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsRow{}
	for rows.Next() {
		var i SettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :execrows
UPDATE menus SET title = $2, url = $3, parent_id = nullif($5::text, '')::uuid, sort_order = $4
WHERE id = $1
`

type UpdateMenuItemParams struct {
	ID        string
	Title     string
	Url       string
	SortOrder int32
	ParentID  string
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMenuItem,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.SortOrder,
		arg.ParentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePage = `-- name: UpdatePage :execrows
UPDATE pages SET slug = $2, title = $3, body = $4, template = $5, updated_at = now()
WHERE id = $1
`

type UpdatePageParams struct {
	ID       string
	Slug     string
	Title    string
	Body     string
	Template string
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePage,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.Template,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
